/**
 * @JackettDefinitions https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/13city.yml
 * @JackettIssue https://github.com/Jackett/Jackett/issues/16052
 */
import { type ISiteMetadata } from "../types";
import { CategoryIncldead, CategorySpstate, CategoryInclbookmarked, SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,
  id: "13city",
  name: "13city",
  aka: ["13城"],
  description: "一切美好源于分享",
  tags: ["影视", "综合"],
  timezoneOffset: "+0800",
  collaborator: ["13City"],
  type: "private",
  schema: "NexusPHP",
  urls: ["https://13city.org/", "https://www.13city.org/"],
  formerHosts: ["13city.online"],
  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      bonus: {
        selector: ["td.rowhead:contains('啤酒瓶') + td, td.rowhead:contains('Karma Points') + td"],
        filters: [{ name: "parseNumber" }],
      },
    },
  },
  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "电影/Movies", value: 401 },
        { name: "连续剧/TV Series", value: 402 },
        { name: "综艺/TV Shows", value: 403 },
        { name: "动漫/Animations", value: 405 },
        { name: "演唱会、MV/Music Videos", value: 406 },
        { name: "音乐/Music", value: 408 },
        { name: "有声小说/E-book", value: 409 },
        { name: "纪录片/Documentaries", value: 413 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "Blu-ray", value: 1 },
        { name: "HD DVD", value: 2 },
        { name: "Remux", value: 3 },
        { name: "MiniBD", value: 4 },
        { name: "HDTV", value: 5 },
        { name: "DVDR", value: 6 },
        { name: "Encode", value: 7 },
        { name: "CD", value: 8 },
        { name: "Track", value: 9 },
        { name: "WEB-DL", value: 10 },
        { name: "BluRay", value: 11 },
        { name: "WEBRip", value: 12 },
        { name: "Other", value: 13 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "AVC/H.264/x264", value: 1 },
        { name: "HEVC/H.265/x265", value: 2 },
        { name: "MPEG-2", value: 3 },
        { name: "VC-1", value: 4 },
        { name: "VPB/VP9", value: 5 },
        { name: "Xvid", value: 6 },
        { name: "Other", value: 7 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "FLAC", value: 1 },
        { name: "APE", value: 2 },
        { name: "DTS-HD/DTS", value: 3 },
        { name: "MP3", value: 4 },
        { name: "OGG", value: 5 },
        { name: "AAC", value: 6 },
        { name: "DDP/E-AC3", value: 7 },
        { name: "TrueHD", value: 8 },
        { name: "TrueHD Atmos", value: 9 },
        { name: "LPCM", value: 10 },
        { name: "Other", value: 11 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "8K", value: 1 },
        { name: "4K", value: 3 },
        { name: "1080p", value: 4 },
        { name: "1080i", value: 5 },
        { name: "Other", value: 6 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "区域",
      key: "Processing",
      options: [
        { name: "中国（含港澳台）", value: 1 },
        { name: "日本", value: 2 },
        { name: "泰国", value: 3 },
        { name: "印度", value: 4 },
        { name: "韩国", value: 5 },
        { name: "欧美", value: 6 },
        { name: "Other（其他）", value: 7 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "13City", value: 1 },
        { name: "AilMWeb", value: 2 },
        { name: "52pt", value: 3 },
        { name: "HHWEB", value: 4 },
        { name: "CHDWEB", value: 5 },
        { name: "FRDS", value: 6 },
        { name: "MTeam", value: 7 },
        { name: "QHstudIo", value: 8 },
        { name: "PTerWEB", value: 9 },
        { name: "rainweb", value: 10 },
        { name: "Other", value: 11 },
        { name: "SewageWeb", value: 12 },
        { name: "UBWEB", value: 13 },
        { name: "ZmWeb", value: 14 },
        { name: "ADWeb", value: 15 },
        { name: "UBits", value: 16 },
        { name: "WiKi", value: 17 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 1,
      name: "Peasant",
      nameAka: ["小菜鸡"],
      privilege:
        "当以下情况时将被自动降至本级：1.如果你已经下载了超过64GB，你应该有大于0.5的分享率。2.如果你已经下载了超过256GB，你应该有大于0.6的分享率。3.如果你已经下载了超过512GB，你应该有大于0.7的分享率。4.如果你已经下载了超过768GB，你应该有大于0.8的分享率。5.如果你已经下载了超过1024GB，你应该有大于0.9的分享率。",
    },
    {
      id: 2,
      name: "User",
      nameAka: ["初窥门径"],
      privilege: "新用户的默认级别",
    },
    {
      id: 3,
      name: "Power User",
      nameAka: ["小有所成"],
      interval: "P4W",
      downloaded: "256GB",
      ratio: 1.05,
      privilege: "首次升级至此等级的用户将获得1个邀请名额。",
    },
    {
      id: 4,
      name: "Elite User",
      nameAka: ["懵懂求知"],
      interval: "P8W",
      downloaded: "512GB",
      ratio: 1.55,
      privilege: "首次升级至此等级的用户将获得0个邀请名额。",
    },
    {
      id: 5,
      name: "Crazy User",
      nameAka: ["小试牛刀"],
      interval: "P15W",
      downloaded: "1024GB",
      ratio: 2.05,
      privilege: "首次升级至此等级的用户将获得2个邀请名额。",
    },
    {
      id: 6,
      name: "Insane User",
      nameAka: ["渐入佳境"],
      interval: "P25W",
      downloaded: "2048GB",
      ratio: 2.55,
      privilege: "首次升级至此等级的用户将获得0个邀请名额。",
    },
    {
      id: 7,
      name: "Veteran User",
      nameAka: ["游刃有余"],
      interval: "P50W",
      downloaded: "3072GB",
      ratio: 3.05,
      privilege: "首次升级至此等级的用户将获得3个邀请名额。",
    },
    {
      id: 8,
      name: "Extreme User",
      nameAka: ["登堂入室"],
      interval: "P100W",
      downloaded: "4096GB",
      ratio: 3.55,
      privilege: "首次升级至此等级的用户将获得0个邀请名额。",
    },
    {
      id: 9,
      name: "Ultimate User",
      nameAka: ["炉火纯青"],
      interval: "P150W",
      downloaded: "6144GB",
      ratio: 4.05,
      privilege: "首次升级至此等级的用户将获得5个邀请名额。",
    },
    {
      id: 10,
      name: "Nexus Master",
      nameAka: ["返璞归真"],
      interval: "P240W",
      downloaded: "8192GB",
      ratio: 4.55,
      privilege: "首次升级至此等级的用户将获得10个邀请名额。",
    },
  ],
};
