/**
 * @JackettDefinitions https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/audionews.yml
 * @JackettIssue https://github.com/Jackett/Jackett/issues/4181
 */
import type { ISiteMetadata } from "../types.ts";
import { buildCategoryOptionsFromDict } from "../utils.ts";

const categoryMap: Record<number, string> = {
  106: "Mobile Apps",
  161: "Mobile Apps iOS",
  160: "Mobile Apps Android",
  12: "AUDIOAPPS",
  32: "AUDIOAPPS DAW Apps",
  175: "AUDIOAPPS Ableton",
  177: "AUDIOAPPS Cakewalk",
  176: "AUDIOAPPS REAPER",
  174: "AUDIOAPPS Steinberg",
  34: "AUDIOAPPS Mastering &Audio Editor Apps",
  37: "AUDIOAPPS DJ Apps",
  13: "SAMPLE LIBRARIES",
  62: "SAMPLE LIBRARIES AMG",
  117: "SAMPLE LIBRARIES Bela D Media",
  118: "SAMPLE LIBRARIES Beta Monkey Music",
  51: "SAMPLE LIBRARIES Best Service",
  46: "SAMPLE LIBRARIES Big Fish",
  66: "SAMPLE LIBRARIES Bigga Giggas",
  122: "SAMPLE LIBRARIES Bluezone Corporation",
  123: "SAMPLE LIBRARIES Bunker 8",
  126: "SAMPLE LIBRARIES Cinematique Instruments",
  127: "SAMPLE LIBRARIES CineSamples",
  128: "SAMPLE LIBRARIES ClusterSound",
  121: "SAMPLE LIBRARIES Dan Dean",
  195: "SAMPLE LIBRARIES Diginoiz",
  52: "SAMPLE LIBRARIES Digital Juice",
  134: "SAMPLE LIBRARIES Digital-Redux",
  65: "SAMPLE LIBRARIES Digital Vision",
  59: "SAMPLE LIBRARIES Discovery Firm",
  61: "SAMPLE LIBRARIES Drumdrops",
  40: "SAMPLE LIBRARIES East West",
  74: "SAMPLE LIBRARIES Electronisounds",
  80: "SAMPLE LIBRARIES EMU format",
  82: "SAMPLE LIBRARIES ENSONIQ format",
  111: "SAMPLE LIBRARIES Fatloud",
  135: "SAMPLE LIBRARIES Fox Samples",
  41: "SAMPLE LIBRARIES FxPansion",
  130: "SAMPLE LIBRARIES Goldbaby",
  54: "SAMPLE LIBRARIES Hollywood Edge",
  64: "SAMPLE LIBRARIES IK Multimedia",
  75: "SAMPLE LIBRARIES Ilio",
  108: "SAMPLE LIBRARIES Industrial Strength Records",
  81: "SAMPLE LIBRARIES KURZWEIL format",
  91: "SAMPLE LIBRARIES Loopmasters",
  92: "SAMPLE LIBRARIES Masterbits",
  58: "SAMPLE LIBRARIES M-Audio",
  112: "SAMPLE LIBRARIES Mutekki",
  137: "SAMPLE LIBRARIES Mystic Kingz",
  47: "SAMPLE LIBRARIES Native Instruments",
  60: "SAMPLE LIBRARIES Nine Volt Audio",
  129: "SAMPLE LIBRARIES OrangeTree",
  203: "SAMPLE LIBRARIES Origin Sound",
  154: "SAMPLE LIBRARIES P5Audio",
  133: "SAMPLE LIBRARIES Peace Love Productions",
  140: "SAMPLE LIBRARIES Pound Audio",
  110: "SAMPLE LIBRARIES Prime Loops",
  180: "SAMPLE LIBRARIES Producer Loops",
  50: "SAMPLE LIBRARIES Prominy",
  171: "SAMPLE LIBRARIES Pulsed Records",
  132: "SAMPLE LIBRARIES Puremagnetik",
  49: "SAMPLE LIBRARIES Refills",
  99: "SAMPLE LIBRARIES reFX Nexus",
  125: "SAMPLE LIBRARIES Realsamples",
  83: "SAMPLE LIBRARIES ROLAND format",
  109: "SAMPLE LIBRARIES Sample Magic",
  136: "SAMPLE LIBRARIES Samplephonics",
  43: "SAMPLE LIBRARIES Sampletekk",
  48: "SAMPLE LIBRARIES Scarbee",
  178: "SAMPLE LIBRARIES SFX (Sound FX libraries)",
  90: "SAMPLE LIBRARIES Smartsound",
  172: "SAMPLE LIBRARIES Sonart Audio",
  116: "SAMPLE LIBRARIES SonicCouture",
  42: "SAMPLE LIBRARIES Sonic Implants",
  115: "SAMPLE LIBRARIES Sonic Reality",
  53: "SAMPLE LIBRARIES Sound Ideas",
  56: "SAMPLE LIBRARIES Sony",
  139: "SAMPLE LIBRARIES Sounds To Sample",
  76: "SAMPLE LIBRARIES Spectrasonics",
  162: "SAMPLE LIBRARIES Spitfire Audio",
  193: "SAMPLE LIBRARIES studiolinked",
  68: "SAMPLE LIBRARIES Synthogy",
  179: "SAMPLE LIBRARIES The Loop Loft",
  96: "SAMPLE LIBRARIES Tonehammer, 8dio, SoundIron",
  67: "SAMPLE LIBRARIES Toontrack, Drumkit From Hell, DFHS",
  69: "SAMPLE LIBRARIES Ueberschall",
  157: "SAMPLE LIBRARIES USB Soundscan",
  120: "SAMPLE LIBRARIES Valentino Production",
  173: "SAMPLE LIBRARIES vandalism sounds",
  170: "SAMPLE LIBRARIES Vanilla Groove Studios",
  119: "SAMPLE LIBRARIES Vengeance Sound",
  114: "SAMPLE LIBRARIES Video Helper",
  44: "SAMPLE LIBRARIES Vienna",
  77: "SAMPLE LIBRARIES Vipzone",
  131: "SAMPLE LIBRARIES Wavesfactory",
  89: "SAMPLE LIBRARIES West one",
  113: "SAMPLE LIBRARIES Wusik.com",
  78: "SAMPLE LIBRARIES Yellowtools",
  138: "SAMPLE LIBRARIES YnK.Audio",
  100: "SAMPLE LIBRARIES Zenhiser",
  57: "SAMPLE LIBRARIES Zero-G",
  15: "VSTi + FX",
  72: "VSTi + FX FX",
  181: "VSTi + FX VSTi",
  18: "MAC",
  186: "MAC Apps",
  188: "MAC FX",
  189: "MAC Instruments",
  190: "MAC TUTORIAL",
  187: "MAC Samples",
  19: "MISC",
  185: "MISC Utilities",
  84: "SHEET MUSIC",
  87: "SHEET MUSIC Full Score",
  86: "SHEET MUSIC Guitar",
  88: "SHEET MUSIC Other instruments",
  85: "SHEET MUSIC Piano",
  20: "LEARNING",
  197: "LEARNING Academy.FM",
  183: "LEARNING ADSR",
  141: "LEARNING Alfred",
  142: "LEARNING Ask Video",
  27: "LEARNING Books",
  143: "LEARNING FaderPro",
  144: "LEARNING Groove3",
  145: "LEARNING Hal Leonard",
  105: "LEARNING Hardware manuals",
  196: "LEARNING Jam Track Central",
  146: "LEARNING Lick Library",
  147: "LEARNING Lynda.com",
  148: "LEARNING MacProVideo",
  101: "LEARNING Magazines",
  93: "LEARNING Music Video (Concerts, DVD, DVDrip)",
  199: "LEARNING PUREMIX",
  149: "LEARNING Riff Interactive",
  194: "LEARNING SkillShare",
  150: "LEARNING Sonic Academy",
  151: "LEARNING Total training",
  152: "LEARNING TrueFire",
  182: "LEARNING Udemy",
  28: "LEARNING Video",
  153: "LEARNING VTC",
  29: "PRESETS",
  167: "PRESETS Ableton Live",
  184: "PRESETS Impulse Responses",
  166: "PRESETS Massive",
  163: "PRESETS Nebula",
  200: "PRESETS Omnisphere",
  165: "PRESETS Reaktor",
  201: "PRESETS Xfer Serum",
  164: "PRESETS Sylenth",
  168: "PRESETS Toontrack",
  239: "Service Manuals",
  21: "UPDATE",
  222: "GFXNEWS 3D",
  235: "GFXNEWS APPS ANDROID & IOS",
  207: "GFXNEWS APPS WIN",
  215: "GFXNEWS APPS LINUX",
  214: "GFXNEWS APPS MAC",
  211: "GFXNEWS BOOKS",
  224: "GFXNEWS CAD/CAM",
  237: "GFXNEWS DAZ3D",
  212: "GFXNEWS FONTS",
  213: "GFXNEWS FOOTAGE",
  233: "GFXNEWS GAME DEVELOPMENT",
  226: "GFXNEWS MAGAZINE",
  234: "GFXNEWS MATERIAL",
  243: "GFXNEWS OTHER GRAPHICS",
  244: "GFXNEWS OTHER GRAPHICS Zbrush, Substance tools",
  216: "GFXNEWS PHOTOSTOCK",
  220: "GFXNEWS PHOTOGRAPHY - ART",
  227: "GFXNEWS 2D Graphics",
  250: "GFXNEWS 2D Graphics Effects",
  228: "GFXNEWS 2D Graphics Actions, Pattern & Styles",
  229: "GFXNEWS 2D Graphics Background & PSD Source",
  230: "GFXNEWS 2D Graphics Brushes & Gradient",
  246: "GFXNEWS 2D Graphics Mockup",
  247: "GFXNEWS 2D Graphics Overlays",
  249: "GFXNEWS 2D Graphics Preset",
  231: "GFXNEWS 2D Graphics Toolkits, Papers & Objects",
  245: "GFXNEWS GFX Plugins",
  210: "GFXNEWS PLUGINS WIN",
  223: "GFXNEWS PLUGINS MAC",
  225: "GFXNEWS PLUGINS LINUX",
  217: "GFXNEWS SCRIPTS - WEB PROGRAMMING",
  218: "GFXNEWS TEMPLATES",
  232: "GFXNEWS TEXTURES",
  219: "GFXNEWS TUTORIALS",
  238: "GFXNEWS VECTOR GRAPHICS",
  221: "GFXNEWS VIDEO PRODUCTION",
};

export const siteMetadata: ISiteMetadata = {
  version: 2,
  id: "audionews",
  name: "AudioNews",
  aka: ["AN"],
  description: "AudioNews (AN) is a Private Torrent Tracker for AUDIO SOFTWARE / SAMPLES / ETC",
  tags: ["软件", "0day", "素材", "学习", "音乐制作"],
  timezoneOffset: "-0700",

  type: "private",
  schema: "AbstractPrivateSite",

  urls: ["https://audionews.org/"],

  category: [
    {
      name: "类别",
      key: "f",
      keyPath: "data",
      options: buildCategoryOptionsFromDict(categoryMap),
      cross: { mode: "brackets" },
    },
  ],

  search: {
    skipNonLatinCharacters: true,
    keywordPath: "data.nm",
    requestConfig: {
      url: "/tracker.php",
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      data: {
        prev_allw: 1,
        prev_a: 0,
        prev_dla: 0,
        prev_dlc: 0,
        prev_dld: 0,
        prev_dlw: 0,
        prev_my: 0,
        prev_new: 0,
        prev_sd: 0,
        prev_da: 1,
        prev_dc: 0,
        prev_df: 1,
        prev_ds: 0,
        pre_tor_type: 0,
        prev_date_from: "",
        prev_date_to: "",
        prev_hide_rereg: 0,
        o: 1, // sort by, 1 created 2 title 7 size 10 seeders
        s: 2, // sort order, 1 asc 2 desc
        df: 1,
        da: 1,
        pn: "",
        submit: "Search",
      },
      responseType: "document",
    },
    advanceKeywordParams: {
      imdb: false,
    },
    selectors: {
      rows: { selector: "table.tracker-table > tbody > tr.tracker-row:has(a[href*='/dl.php?id='])" },
      time: { selector: ":self", data: "torDate", filters: [{ name: "parseTime", args: ["dd_MM_yyyy"] }] },
      title: { selector: "td a[href*='/viewtopic.php?t=']" },
      url: { selector: "td a[href*='/viewtopic.php?t=']", attr: "href" },
      id: { selector: "td a[href*='/dl.php?id=']", attr: "href", filters: [{ name: "querystring", args: ["id"] }] },
      link: { selector: "td a[href*='/dl.php?id=']", attr: "href" },
      category: {
        selector: "td a[href*='/tracker.php?f=']",
        attr: "href",
        filters: [{ name: "querystring", args: ["f"] }, (query: number) => categoryMap[query]],
      },
      size: {
        text: 0,
        selector: ["td:contains(\u00A0GB)", "td:contains(\u00A0MB)", "td:contains(\u00A0KB)", "td:contains(\u00A0B)"],
        filters: [{ name: "parseSize" }],
      },
      seeders: { selector: "td[title='Seeders']" },
      leechers: { selector: "td[title='Leechers']" },
      completed: { selector: "td[title^='Replies:']" },
      comments: { text: 0, selector: "span.tracker_topic_replies a" },
      author: { selector: "td a[href*='/tracker.php?pid=']" },
    },
  },

  detail: {
    urlPattern: ["/viewtopic\\.php\\?t=\\d+"],
    selectors: {
      title: { selector: "a.tt-text[href^='viewtopic.php?t=']" },
      link: { selector: "a[href^='dl.php?id=']", attr: "href" },
    },
  },

  userInfo: {
    pickLast: ["id"],
    process: [
      {
        requestConfig: { url: "/index.php", responseType: "document" },
        selectors: {
          id: { selector: "a.user_photo[title='Your profile'] img", attr: "alt" },
        },
      },
      {
        requestConfig: { url: "/profile.php", params: { mode: "viewprofile" }, responseType: "document" },
        assertion: { id: "params.u" },
        selectors: {
          name: { selector: "#username" },
          levelName: { selector: "b#rank-name" },
          joinTime: { selector: "#user_regdate", filters: [{ name: "parseTime" }] },
          lastAccessAt: { selector: "#user_lastvisit", filters: [{ name: "parseTime" }] },
          ratio: { selector: "#bt_user_ratio > b", filters: [{ name: "parseNumber" }] },
          downloaded: { selector: "td#u_down_total > span", filters: [{ name: "parseSize" }] },
          uploaded: { selector: "td#u_up_total > span", filters: [{ name: "parseSize" }] },
          seeding: {
            text: 0,
            selector: "span.dls-cnt",
            filters: [
              (query: string) => {
                return query.match(/Seed: (\d+)/)?.[1];
              },
            ],
          },
          uploads: {
            text: 0,
            selector: "span.dls-cnt",
            filters: [
              (query: string) => {
                return query.match(/Self: (\d+)/)?.[1];
              },
            ],
          },
          // seedingSize: { text: "N/A" },
          bonus: { text: "N/A" },
          bonusPerHour: { text: "N/A" },
        },
      },
    ],
  },
};
