import { type ISiteMetadata } from "../types";
import { CategoryFree, SchemaMetadata } from "../schemas/Unit3D";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,
  id: "clearjav",
  name: "ClearJAV",
  tags: ["成人", "xxx"],
  timezoneOffset: "+0200",
  collaborator: ["Jamyiz"],

  type: "private",
  schema: "Unit3D",

  urls: ["https://clearjav.com/"],

  search: {
    ...SchemaMetadata.search,
    selectors: {
      ...SchemaMetadata.search!.selectors,
      rows: { selector: "tr.torrent-search--list__row" },
      id: { selector: ":self", attr: "data-torrent-id" },
      title: { selector: "div.torrent-title > a" },
      url: { selector: "div.torrent-title > a", attr: "href" },
      link: { selector: "a[href*='/torrents/download/']", attr: "href" },

      subTitle: {
        selector: "div.meta-list",
        filters: [
          (query: string) => {
            return query.trim().replace(/\s+/g, " | ");
          },
        ],
      },
      category: {
        selector: "div.torrent-search--list__resolution-and-type > span",
      },
      size: { selector: "td.torrent-search--list__size > span", filters: [{ name: "parseSize" }] },
      time: { selector: "td.torrent-search--list__age > time", attr: "datetime", filters: [{ name: "parseTime" }] },

      seeders: { selector: "td.torrent-search--list__seeders > a" },
      leechers: { selector: "td.torrent-search--list__leechers > a" },
      completed: { selector: "td.torrent-search--list__completed > a" },
      author: { selector: "span.user-tag.torrent-search--list__uploader > a.user-tag__link" },

      tags: [
        { name: "Free", selector: "i.torrent-icons__freeleech.fa-star", color: "blue" },
        { name: "高速", selector: "i.torrent-icons__highspeed", color: "green" },
        { name: "4K", selector: "div.meta-list > a.category:contains('4K')", color: "red" },
      ],
    },
  },

  levelRequirements: [
    {
      id: 3,
      name: "User",
      privilege: "基础用户权限",
    },
    {
      id: 11,
      name: "PowerUser",
      uploaded: "1TB",
      interval: "P30D",
      ratio: 0.4,
    },
    {
      id: 12,
      name: "SuperUser",
      uploaded: "5TB",
      interval: "P60D",
      ratio: 0.4,
    },
    {
      id: 13,
      name: "ExtremeUser",
      uploaded: "20TB",
      interval: "P90D",
      ratio: 0.4,
    },
    {
      id: 14,
      name: "InsaneUser",
      uploaded: "50TB",
      interval: "P180D",
      ratio: 0.4,
    },
    {
      id: 17,
      name: "Seeder",
      seedingSize: "5TB",
      averageSeedingTime: "P30D",
      interval: "P30D",
      ratio: 0.4,
    },
  ],

  category: [
    {
      name: "规格",
      key: "types",
      options: [
        { name: "Remux", value: 2 },
        { name: "WEB-DL", value: 4 },
      ],
      cross: { mode: "brackets" },
    },
    {
      name: "分辨率",
      key: "resolutions",
      options: [
        { name: "8K-VR", value: 14 },
        { name: "VR", value: 13 },
        { name: "2160p", value: 2 },
        { name: "1080p", value: 3 },
        { name: "720p", value: 5 },
        { name: "576p", value: 6 },
        { name: "480p", value: 8 },
        { name: "404p", value: 11 },
        { name: "SD", value: 15 },
        { name: "Other", value: 16 },
      ],
      cross: { mode: "brackets" },
    },
    {
      name: "类别 (Categories)",
      key: "categories",
      options: [
        { name: "4K", value: 1530 },
        { name: "69", value: 3679 },
        { name: "8KVR", value: 3710 },
        { name: "Abuse", value: 3560 },
        { name: "Academy Uniform", value: 1112 },
        { name: "Action", value: 3467 },
        { name: "Action & Fighting", value: 3615 },
        { name: "Actress Best Compilation", value: 3509 },
        { name: "Adult Summer Campaign", value: 3691 },
        { name: "Adultery", value: 1153 },
        { name: "Amateur", value: 1238 },
        { name: "Anal Play", value: 1304 },
        { name: "Anal Sex", value: 1364 },
        { name: "Anime Character", value: 3431 },
        { name: "Ass Lover", value: 1226 },
        { name: "Athlete", value: 3574 },
        { name: "Auntie", value: 3556 },
        { name: "AV Grand Prix", value: 3703 },
        { name: "AV Loves Campaign", value: 3690 },
        { name: "AV Open 2014 Middleweight", value: 3505 },
        { name: "AV OPEN 2015 Kink/Fetish Division", value: 3522 },
        { name: "AV OPEN 2015 S&M/Hardcore Division", value: 3520 },
        { name: "AV OPEN 2015 Variety Show Division", value: 3519 },
        { name: "AV OPEN 2015 Virgin Division", value: 3523 },
        { name: "AV OPEN 2016 Hardcore Division", value: 3531 },
        { name: "AV OPEN 2016 Planning Division", value: 3527 },
        { name: "AV OPEN 2017 Hardcare Category", value: 3541 },
        { name: "AV OPEN 2017 Maiden Division", value: 3720 },
        { name: "AV OPEN 2017 Mania Category", value: 3537 },
        { name: "AV OPEN 2017 Project Category", value: 3536 },
        { name: "Bath", value: 3576 },
        { name: "BDSM", value: 1216 },
        { name: "Beautiful Girl", value: 1120 },
        { name: "Beautiful Tits", value: 1086 },
        { name: "Big Asses", value: 1185 },
        { name: "BIG Sale", value: 3704 },
        { name: "BIG Sale Part 2", value: 3707 },
        { name: "Big Tits", value: 1167 },
        { name: "Big Tits Lover", value: 3458 },
        { name: "Big Vibrator", value: 1354 },
        { name: "Birgin", value: 3729 },
        { name: "Bitch", value: 1400 },
        { name: "Black Man", value: 3441 },
        { name: "Blonde", value: 3591 },
        { name: "Blowjob", value: 1301 },
        { name: "Blu-ray (Blu-ray)", value: 3695 },
        { name: "Bondage", value: 1198 },
        { name: "Breast Milk", value: 3483 },
        { name: "Bride", value: 3501 },
        { name: "BUKKAKE", value: 1775 },
        { name: "Bunny Girl", value: 1212 },
        { name: "Bus Tour Guide", value: 3439 },
        { name: "Business Suit", value: 3553 },
        { name: "Campaign Girl", value: 3435 },
        { name: "Candle Drippings", value: 3564 },
        { name: "Car Sex", value: 1240 },
        { name: "Cat Cosplay", value: 3612 },
        { name: "Caucasian Actress", value: 3448 },
        { name: "Celeb", value: 1477 },
        { name: "Cell Specification", value: 3721 },
        { name: "chat lady", value: 3732 },
        { name: "Cheating", value: 3727 },
        { name: "Cheating Wife", value: 1287 },
        { name: "Cheerleader", value: 3568 },
        { name: "Cherry Boy", value: 1228 },
        { name: "Chinese Dress", value: 3451 },
        { name: "Chubby", value: 1173 },
        { name: "Classics", value: 3461 },
        { name: "Club Hostess & Sex Worker", value: 1128 },
        { name: "Club Manager", value: 3570 },
        { name: "Collaborative Work", value: 3504 },
        { name: "College Girl", value: 1586 },
        { name: "Comedy", value: 3420 },
        { name: "Compilation", value: 3682 },
        { name: "Conception", value: 3700 },
        { name: "Confessional", value: 3495 },
        { name: "Confinement", value: 1309 },
        { name: "Coprophagy", value: 3480 },
        { name: "Cosplay", value: 1244 },
        { name: "Couple", value: 1295 },
        { name: "Couple Swapping", value: 1492 },
        { name: "Cowgirl", value: 1283 },
        { name: "Creampie", value: 1300 },
        { name: "Cross Dresser", value: 1215 },
        { name: "Cum Swallowing", value: 1308 },
        { name: "Cunnilingus", value: 1071 },
        { name: "Cute-Goth", value: 3454 },
        { name: "Dance", value: 3470 },
        { name: "Date", value: 1478 },
        { name: "Daydream", value: 1241 },
        { name: "Daydreamers", value: 1497 },
        { name: "Debut", value: 1369 },
        { name: "Deep Throat", value: 1356 },
        { name: "Delusional Tribe, Emmanuelle Serre", value: 3715 },
        { name: "Digital Mosaic", value: 1367 },
        { name: "Dildo", value: 3706 },
        { name: "Dirty Talk", value: 1324 },
        { name: "Disc On Demand Sale", value: 3698 },
        { name: "Documentary", value: 1237 },
        { name: "DOD Genre Sale (Mature Woman/Married Woman)", value: 3724 },
        { name: "Doggystyle", value: 3567 },
        { name: "Doll", value: 3424 },
        { name: "Domination", value: 3421 },
        { name: "Drama", value: 1288 },
        { name: "Drinking Party/Mixer", value: 3566 },
        { name: "dripping love juice", value: 3734 },
        { name: "Drunk", value: 3475 },
        { name: "DVD Lottery Coupon Eligible", value: 3716 },
        { name: "Early 2020s (DOD)", value: 3697 },
        { name: "Egg Vibrator", value: 3677 },
        { name: "Embarrassment", value: 1067 },
        { name: "Emmanuel", value: 3580 },
        { name: "Employee/Coworker", value: 3558 },
        { name: "Enema", value: 1786 },
        { name: "Estrus", value: 3735 },
        { name: "Exclusive Distribution", value: 1407 },
        { name: "Exclusive Rentals", value: 3702 },
        { name: "Exorcist & Nun", value: 3638 },
        { name: "Eyes-Roll-Back, Fainting", value: 3575 },
        { name: "Face Sitting", value: 1355 },
        { name: "Facial", value: 1322 },
        { name: "Facing Sitting", value: 3736 },
        { name: "Fall BIG Sale", value: 3693 },
        { name: "Fan Appreciation/ Home Visit", value: 3476 },
        { name: "Fantasy", value: 3601 },
        { name: "FANZA 5th Anniversary Campaign", value: 3699 },
        { name: "Featured Actress", value: 1239 },
        { name: "Female Anchor", value: 3626 },
        { name: "Female Boss", value: 1467 },
        { name: "Female Detective", value: 3449 },
        { name: "Female Doctor", value: 3624 },
        { name: "Female Ninja", value: 3640 },
        { name: "Female Porn Star", value: 3714 },
        { name: "Female Soldier", value: 3641 },
        { name: "Female Teacher", value: 1110 },
        { name: "Fingering", value: 1345 },
        { name: "Fisting", value: 3427 },
        { name: "Flexible body", value: 1458 },
        { name: "Foot Fetish", value: 3457 },
        { name: "Footjob", value: 3481 },
        { name: "For Women", value: 3423 },
        { name: "Foreign Imports", value: 3460 },
        { name: "G-Spot", value: 1380 },
        { name: "Gal", value: 1127 },
        { name: "Gang Bang", value: 1069 },
        { name: "Gay", value: 3464 },
        { name: "Genital Clos-Up", value: 3731 },
        { name: "Genital Close-Up", value: 1231 },
        { name: "Glasses", value: 1170 },
        { name: "Golden Shower", value: 3478 },
        { name: "Gonzo", value: 1365 },
        { name: "Groping", value: 3664 },
        { name: "GW Great Thanksgiving Festival", value: 3712 },
        { name: "Gym Clothes", value: 1186 },
        { name: "Gyno Exam", value: 3477 },
        { name: "Gyno Examo", value: 3733 },
        { name: "Handjob", value: 1303 },
        { name: "Hard Sex", value: 3621 },
        { name: "Harem", value: 3487 },
        { name: "Hermaphrodite", value: 3609 },
        { name: "Hi-Def", value: 1399 },
        { name: "High-Quality VR", value: 3709 },
        { name: "Homemade", value: 1368 },
        { name: "Hospital/Clinic", value: 3572 },
        { name: "Hostess", value: 3444 },
        { name: "Hot Spring", value: 1299 },
        { name: "Hotel", value: 3571 },
        { name: "Housewife", value: 1099 },
        { name: "How To", value: 3494 },
        { name: "Huge Dick - Large Dick", value: 1361 },
        { name: "Huge Tits", value: 3499 },
        { name: "Hypnotism", value: 3484 },
        { name: "Idol & Celebrity", value: 1144 },
        { name: "Idol Video", value: 3491 },
        { name: "illustrator", value: 3739 },
        { name: "Instructor", value: 3434 },
        { name: "Interview", value: 3551 },
        { name: "JET Video 40% Off Sale", value: 3719 },
        { name: "KIMONO", value: 3653 },
        { name: "Kiss Kiss", value: 1264 },
        { name: "Knee-High Socks", value: 3428 },
        { name: "Leotards", value: 3455 },
        { name: "Lesbian", value: 1227 },
        { name: "Lesbian Kissing", value: 1350 },
        { name: "Lingerie", value: 3660 },
        { name: "Live Game Filming Edition", value: 3508 },
        { name: "Long Hair", value: 3588 },
        { name: "Lookalike", value: 3443 },
        { name: "Loose Socks", value: 3453 },
        { name: "Lotion", value: 1346 },
        { name: "Love", value: 3432 },
        { name: "M-jo", value: 1489 },
        { name: "Maid", value: 1576 },
        { name: "Married Woman", value: 1129 },
        { name: "Martial Arts", value: 3629 },
        { name: "Mask", value: 3562 },
        { name: "Masochist Man", value: 1362 },
        { name: "Massage", value: 1296 },
        { name: "Massage Parlor", value: 3473 },
        { name: "Masturbation", value: 1307 },
        { name: "Masturbation Support", value: 3552 },
        { name: "Mature And Married Woman Campaign", value: 3726 },
        { name: "Mature Woman", value: 1108 },
        { name: "Mercury & FirstStar & War 40% Off Sale", value: 3718 },
        { name: "Mercury & FirstStar 50% Off Sale", value: 3705 },
        { name: "MILF", value: 3633 },
        { name: "Minimal Mosaic", value: 1375 },
        { name: "Miniskirt", value: 3656 },
        { name: "Missionary", value: 3730 },
        { name: "Model", value: 3437 },
        { name: "Mom Friends", value: 3569 },
        { name: "MOODYZ Campaign", value: 3696 },
        { name: "More Than 16 Hours Of Footage", value: 3510 },
        { name: "Muscular", value: 3430 },
        { name: "Naked Apron", value: 3613 },
        { name: "Neglect", value: 3563 },
        { name: "New Year's Eve Sale", value: 3692 },
        { name: "Newcomers Debut One After Another!", value: 3694 },
        { name: "No Bra", value: 3578 },
        { name: "No Panties", value: 3573 },
        { name: "Non-nude Erotica", value: 3472 },
        { name: "Nose Fuck", value: 3561 },
        { name: "Nurse", value: 1107 },
        { name: "Nymphomaniac", value: 1243 },
        { name: "Object Insertion", value: 3425 },
        { name: "Office Lady", value: 1098 },
        { name: "Old Man", value: 3550 },
        { name: "Old Playmates", value: 3642 },
        { name: "Older Sister", value: 1126 },
        { name: "Orgasm", value: 1402 },
        { name: "Orgy", value: 1220 },
        { name: "Original Collaboration", value: 1297 },
        { name: "Otaku", value: 3565 },
        { name: "Other Fetishes", value: 1225 },
        { name: "Others", value: 3489 },
        { name: "Outdoor", value: 1234 },
        { name: "Over 4 Hours", value: 1372 },
        { name: "Panty Shot", value: 3666 },
        { name: "Pantyhose", value: 3655 },
        { name: "Petite", value: 1169 },
        { name: "Picking Up Girls", value: 3456 },
        { name: "Pink F cup", value: 3737 },
        { name: "Pooping", value: 3479 },
        { name: "POV", value: 1351 },
        { name: "Pranks", value: 1294 },
        { name: "Pregnant", value: 3442 },
        { name: "Premature Ejaculation", value: 3488 },
        { name: "Priestess", value: 3611 },
        { name: "Princess", value: 3618 },
        { name: "Princess & Mademoiselle", value: 1384 },
        { name: "Private Tutor", value: 3630 },
        { name: "Queen", value: 3557 },
        { name: "Quickie", value: 1210 },
        { name: "Race Queen", value: 3438 },
        { name: "Receptionist", value: 3555 },
        { name: "Reluctant", value: 1691 },
        { name: "Reverse Pick Up", value: 3474 },
        { name: "Romantic Comedy", value: 3433 },
        { name: "Rope & Ties", value: 3738 },
        { name: "Ropes & Ties", value: 1066 },
        { name: "S1 Campaign", value: 3723 },
        { name: "Sadism", value: 3482 },
        { name: "Sailor Uniform", value: 3654 },
        { name: "Sale (limited time)", value: 1409 },
        { name: "Sample Video", value: 3689 },
        { name: "Scatology", value: 3599 },
        { name: "School", value: 3619 },
        { name: "School Swimsuits", value: 1193 },
        { name: "School Uniform", value: 1194 },
        { name: "Sci-Fi", value: 3672 },
        { name: "Secretary", value: 3440 },
        { name: "Series", value: 3426 },
        { name: "Serious", value: 3622 },
        { name: "Sex Change/Female Transformation", value: 3429 },
        { name: "Sex Toys", value: 1789 },
        { name: "Sexy", value: 3469 },
        { name: "Shame", value: 1068 },
        { name: "Shaved Pussy", value: 1233 },
        { name: "Shemale", value: 1229 },
        { name: "Shokushu", value: 3610 },
        { name: "Short Hair", value: 3589 },
        { name: "Shotacon", value: 3600 },
        { name: "Sister", value: 3671 },
        { name: "Slender", value: 1172 },
        { name: "Slut", value: 1124 },
        { name: "Small Tits", value: 1171 },
        { name: "Soapland Girl", value: 1460 },
        { name: "SOD Group 40% Off Sale", value: 3701 },
        { name: "Spanking", value: 3554 },
        { name: "Special Effects", value: 3462 },
        { name: "Special Offers And Set Products", value: 3722 },
        { name: "Special Smartphone Vertical Video", value: 3524 },
        { name: "Sports", value: 3468 },
        { name: "Squirting", value: 1315 },
        { name: "StaffPicks01", value: 3511 },
        { name: "StaffPicks02", value: 3512 },
        { name: "StaffPicks03", value: 3513 },
        { name: "StaffPicks04", value: 3514 },
        { name: "StaffPicks05", value: 3515 },
        { name: "StaffPicks06", value: 3516 },
        { name: "Stepfamily", value: 3663 },
        { name: "Stepmom", value: 3616 },
        { name: "Stewardess", value: 3436 },
        { name: "Straight-To-Video", value: 3471 },
        { name: "Substance Use", value: 1314 },
        { name: "Suntan", value: 3450 },
        { name: "Super Heroine", value: 2948 },
        { name: "Swallowing", value: 1470 },
        { name: "Sweating", value: 1363 },
        { name: "Swimsuit", value: 3728 },
        { name: "Swimsuits", value: 1192 },
        { name: "Tall Girl", value: 1168 },
        { name: "Three Dimensional", value: 3725 },
        { name: "Threesome / Foursome", value: 1321 },
        { name: "Tickling", value: 3485 },
        { name: "Tight Dress", value: 1196 },
        { name: "Time Warp", value: 3486 },
        { name: "Titty Fuck", value: 1318 },
        { name: "Titty Shots", value: 3577 },
        { name: "Top 100 Hits In The First Half Of 2021", value: 3717 },
        { name: "Training", value: 1242 },
        { name: "Trip", value: 3579 },
        { name: "Triple HAPPY Campaign", value: 3708 },
        { name: "TSUNDERE", value: 3651 },
        { name: "Uncensored", value: 3713 },
        { name: "Uniform", value: 1073 },
        { name: "Urination", value: 1310 },
        { name: "Variety", value: 1222 },
        { name: "Various Worker", value: 1119 },
        { name: "Vibrator", value: 1305 },
        { name: "Virgin", value: 3608 },
        { name: "Vomit", value: 3500 },
        { name: "Voyeur", value: 1235 },
        { name: "VR Exclusive", value: 3534 },
        { name: "Waitress", value: 1130 },
        { name: "Widow", value: 3631 },
        { name: "Yoga", value: 3549 },
        { name: "Young Wife", value: 1114 },
        { name: "Youthful", value: 3648 },
      ],
      cross: { mode: "brackets" },
    },
    {
      name: "优惠",
      key: "free",
      options: [
        { name: "0% Freeleech", value: 0 },
        { name: "25% Freeleech", value: 25 },
        { name: "50% Freeleech", value: 50 },
        { name: "75% Freeleech", value: 75 },
        { name: "100% Freeleech", value: 100 },
        { name: "Double Upload", value: "doubleup" },
        { name: "Featured", value: "featured" },
        { name: "Refundable", value: "refundable" },
      ],
      cross: { mode: "custom" },
      generateRequestConfig: (selectedOptions) => {
        const params: Record<string, any> = { free: [] };
        (selectedOptions as Array<number | string>).forEach((value) => {
          if (value === "doubleup" || value === "featured" || value === "refundable") {
            params[value] = 1; // 把这三个独立选项转换成 &doubleup=1 的格式
          } else {
            params.free.push(value);
          }
        });
        return { requestConfig: { params } };
      },
    },
    {
      name: "标签 (Tags)",
      key: "tags",
      options: [
        { name: "内部组", value: "internal" },
        { name: "个人发布", value: "personalRelease" },
        { name: "Trumpable", value: "trumpable" },
        { name: "高速", value: "highspeed" },
        { name: "收藏", value: "bookmarked" },
        { name: "想要", value: "wished" },
      ],
      // 这个设置会让选中的值直接加到 URL 里，比如 &internal=1
      cross: { mode: "append", key: "" },
    },
    {
      name: "活跃度 (Health)",
      key: "health",
      options: [
        { name: "存活", value: "alive" },
        { name: "Dying", value: "dying" },
        { name: "Dead", value: "dead" },
        { name: "坟场", value: "graveyard" },
      ],
      cross: { mode: "append", key: "" },
    },
    {
      name: "记录 (Record)",
      key: "record",
      options: [
        { name: "Not Downloaded", value: "notDownloaded" },
        { name: "Downloaded", value: "downloaded" },
        { name: "Seeding", value: "seeding" },
        { name: "Leeching", value: "leeching" },
        { name: "Incomplete", value: "incomplete" },
      ],
      cross: { mode: "append", key: "" },
    },
  ],
};
