import { type ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "crabpt",
  name: "CrabPt",
  aka: ["蟹黄堡"],
  description: "",
  timezoneOffset: "+0800",

  collaborator: ["zzhhxx"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://penocg.ivc/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "电影/Movies", value: 401 },
        { name: "电视剧/TV-Series", value: 402 },
        { name: "综艺/TV-Shows", value: 403 },
        { name: "纪录片/Documentary", value: 404 },
        { name: "动漫/Animation", value: 405 },
        { name: "MV", value: 406 },
        { name: "体育竞技/Sports", value: 407 },
        { name: "音乐/Music", value: 408 },
        { name: "其他/Other", value: 409 },
        { name: "短剧/Playlet", value: 413 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "Other", value: 1 },
        { name: "BluRay", value: 2 },
        { name: "UHD Blu-ray", value: 3 },
        { name: "Remux", value: 4 },
        { name: "Encode", value: 5 },
        { name: "WEB-DL", value: 6 },
        { name: "HDTV", value: 7 },
        { name: "CD", value: 8 },
        { name: "MVC", value: 9 },
        { name: "ProRes", value: 10 },
        { name: "Xvid", value: 11 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "Other", value: 1 },
        { name: "AVC/H.264/x264", value: 2 },
        { name: "HEVC/H.265/x265", value: 3 },
        { name: "H.266/VVC", value: 4 },
        { name: "VP9", value: 5 },
        { name: "AV1", value: 6 },
        { name: "VC-1", value: 14 },
        { name: "MPEG", value: 15 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "Other", value: 1 },
        { name: "AAC", value: 2 },
        { name: "DD/AC3", value: 3 },
        { name: "DDP/E-AC3", value: 4 },
        { name: "DTS", value: 5 },
        { name: "TrueHD", value: 6 },
        { name: "LPCM", value: 7 },
        { name: "DTS:X", value: 8 },
        { name: "MPEG", value: 9 },
        { name: "FLAC", value: 10 },
        { name: "WAV", value: 11 },
        { name: "APE", value: 12 },
        { name: "DTS-HD", value: 15 },
        { name: "ALAC", value: 16 },
        { name: "DTS-HD MA", value: 17 },
        { name: "OGG", value: 21 },
        { name: "DTS-HD", value: 22 },
        { name: "DSD", value: 23 },
        { name: "Opus", value: 24 },
        { name: "Atmos", value: 26 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "Other", value: 1 },
        { name: "720p", value: 2 },
        { name: "1080p/1080i", value: 3 },
        { name: "4K/2160p", value: 4 },
        { name: "8K", value: 5 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "AGSVWEB", value: 15 },
        { name: "DYZ-WEB", value: 11 },
        { name: "DYZ-Movie", value: 12 },
        { name: "DYZ-TV", value: 13 },
        { name: "UBits", value: 9 },
        { name: "HHWEB", value: 8 },
        { name: "FRDS", value: 7 },
        { name: "XHB", value: 6 },
        { name: "OurBits", value: 5 },
        { name: "WiKi", value: 4 },
        { name: "HDS", value: 3 },
        { name: "CHD", value: 2 },
        { name: "Other", value: 1 },
        { name: "Audiences", value: 10 },
        { name: "ZmWeb", value: 16 },
        { name: "MTeam", value: 37 },
        { name: "HDVWEB", value: 36 },
        { name: "HDHome", value: 35 },
        { name: "QHstudIo", value: 34 },
        { name: "beAst", value: 33 },
        { name: "tlf", value: 32 },
        { name: "ZmWeb", value: 31 },
        { name: "FROGWeb", value: 30 },
        { name: "FROG", value: 29 },
        { name: "FRDS", value: 28 },
        { name: "CMCT", value: 27 },
        { name: "WiKi", value: 26 },
        { name: "ADWeb", value: 25 },
        { name: "QHstudIo", value: 24 },
        { name: "PiGoNF", value: 23 },
        { name: "PigoWeb", value: 22 },
        { name: "PigoHD", value: 21 },
        { name: "HDFans", value: 20 },
        { name: "UBWEB", value: 19 },
        { name: "FFans", value: 18 },
        { name: "Pter", value: 17 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别。只能在每周六中午12点至每周日晚上11点59分发布种子。",
    },
    {
      id: 1,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 60000,
      privilege:
        '可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 2,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 120000,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 200000,
      privilege: "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 400000,
      privilege: "可以查看普通日志。",
    },
    {
      id: 5,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 600000,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 3.55,
      seedingBonus: 800000,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 7,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 4.05,
      seedingBonus: 1200000,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 8,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 4.55,
      seedingBonus: 1800000,
      privilege: "得到十个邀请名额。",
    },
  ],
};
