import { type ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "freefarm",
  name: "自由农场",
  aka: ["FreeFarm"],
  description: "自由农场",
  tags: ["电视剧", "韩剧", "日剧"],
  timezoneOffset: "+0800",

  collaborator: ["zhuweitung"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://cg.0ss.pp/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "Movies|电影", value: 401 },
        { name: "TV Series|电视剧", value: 402 },
        { name: "Documentaries|纪录片", value: 403 },
        { name: "TV Shows|综艺", value: 404 },
        { name: "Animations|动漫", value: 405 },
        { name: "Music Videos|音乐视频", value: 406 },
        { name: "HD Music|无损音乐", value: 407 },
        { name: "Sports|体育", value: 408 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "地区",
      key: "source",
      options: [
        { name: "内地 (China,CHN)", value: 35 },
        { name: "香港 (HKG,CHN)", value: 36 },
        { name: "台湾 (TWN,CHN)", value: 37 },
        { name: "韩国 (KOR)", value: 39 },
        { name: "欧美 (Western)", value: 38 },
        { name: "日本 (JPN)", value: 40 },
        { name: "印度 (IND)", value: 41 },
        { name: "泰国 (Th)", value: 34 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "8K/4320P", value: 1 },
        { name: "4K/2160P", value: 2 },
        { name: "1080P", value: 3 },
        { name: "1440P", value: 4 },
        { name: "1080I", value: 5 },
        { name: "720P", value: 6 },
        { name: "SD", value: 7 },
        { name: "其它 (Other)", value: 14 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "UHD Blu-ray", value: 1 },
        { name: "Blu-ray", value: 2 },
        { name: "UHDTV", value: 3 },
        { name: "IPTV", value: 4 },
        { name: "Remux", value: 5 },
        { name: "Encode", value: 6 },
        { name: "HDTV", value: 7 },
        { name: "DVDR", value: 8 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "H.265/HEVC", value: 1 },
        { name: "H.264/AVC", value: 2 },
        { name: "X265", value: 3 },
        { name: "X264", value: 4 },
        { name: "HEVC", value: 5 },
        { name: "VC-1", value: 6 },
        { name: "MPEG-4", value: 7 },
        { name: "MPEG-2", value: 8 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "DTS-HDMA:X 7.1", value: 10 },
        { name: "其它 (Other)", value: 22 },
        { name: "OGG", value: 21 },
        { name: "PCM", value: 17 },
        { name: "DSD", value: 16 },
        { name: "APE", value: 15 },
        { name: "DTS", value: 14 },
        { name: "AAC", value: 13 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "FFWEB/网络视频小组", value: 3 },
        { name: "FFTV/电视录制小组", value: 6 },
        { name: "FFCD/无损小组", value: 4 },
        { name: "其它 (Other)", value: 14 },
        { name: "待定", value: 11 },
        { name: "待定", value: 9 },
        { name: "待定", value: 7 },
        { name: "待定", value: 13 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      // "page": "/mybonus.php",
      bonusPerHour: {
        selector: ['td[rowspan="3"]'],
        filters: [{ name: "parseNumber" }],
      },
    },
  },

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别",
    },
    {
      id: 1,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 40000,
      privilege:
        '可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 2,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 80000,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 150000,
      privilege: "可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 250000,
      privilege: "可以查看普通日志。",
    },
    {
      id: 5,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 400000,
      privilege: "可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 4.55,
      seedingBonus: 800000,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 7,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 5.85,
      seedingBonus: 2000000,
      privilege: "无",
    },
    {
      id: 8,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 6.45,
      seedingBonus: 4000000,
      privilege: "得到十个邀请名额。",
    },
  ],
};
