import { type ISiteMetadata } from "../types";
import { GB, TB } from "../utils";
import { CategoryIncldead, CategorySpstate, CategoryInclbookmarked, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "hdkylin",
  name: "HDKylin",
  description: "与志同道合之人前行 分享更多值得珍藏的资源",
  tags: ["综合", "电影", "电视剧", "纪录片"],
  type: "private",
  schema: "NexusPHP",
  urls: ["uggcf://jjj.uqxly.va/", "uggcf://an.uqxlyva.pbz/", "uggcf://ps.uqxlyva.pbz/"],
  favicon: "https://www.hdkyl.in/favicon.ico",

  levelRequirements: [
    {
      id: 1,
      groupType: "user",
      name: "Peasant(浪迹天涯)",
      privilege:
        "被降级的用户，他们有30天时间来提升分享率，否则他们会被踢。不能发表趣味盒内容；不能申请友情链接；不能上传字幕。",
    },
    {
      id: 2,
      groupType: "user",
      name: "User(草塘结庐)",
      privilege: "新用户的默认级别。",
    },
    {
      id: 3,
      groupType: "user",
      name: "Power User(池畔闲人)",
      seedingBonus: 40000,
      ratio: 2.0,
      interval: "P4W",
      downloaded: 50 * GB,
      privilege: `得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕`,
    },
    {
      id: 4,
      groupType: "user",
      name: "Elite User(五湖信步)",
      seedingBonus: 80000,
      ratio: 3.0,
      interval: "P8W",
      downloaded: 120 * GB,
      privilege: `Elite User及以上用户封存账号后不会被删除。`,
    },
    {
      id: 5,
      groupType: "user",
      name: "Crazy User(轻舟飘渺)",
      seedingBonus: 150000,
      ratio: 4.0,
      interval: "P15W",
      downloaded: 300 * GB,
      privilege: `得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。`,
    },
    {
      id: 6,
      groupType: "user",
      name: "Insane User(长空啸傲)",
      seedingBonus: 250000,
      ratio: 5.0,
      interval: "P25W",
      downloaded: 500 * GB,
      privilege: `  可以查看普通日志。`,
    },
    {
      id: 7,
      groupType: "user",
      name: "Veteran User(江东帆影)",
      seedingBonus: 400000,
      ratio: 6.0,
      interval: "P40W",
      downloaded: 750 * GB,
      privilege: `得到三个邀请名额；可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。`,
    },
    {
      id: 8,
      groupType: "user",
      name: "Extreme User(碧海潮生)",
      seedingBonus: 600000,
      ratio: 7.0,
      interval: "P60W",
      downloaded: 1 * TB,
      privilege: `可以更新过期的外部信息；可以查看Extreme User论坛`,
    },
    {
      id: 9,
      groupType: "user",
      name: "Ultimate User(九州雷动)",
      seedingBonus: 800000,
      ratio: 8.0,
      interval: "P80W",
      downloaded: 4 * TB,
      privilege: `得到五个邀请名额。`,
    },
    {
      id: 10,
      groupType: "user",
      name: "Nexus Master(一鳞半爪)",
      seedingBonus: 1000000,
      ratio: 10.0,
      interval: "P100W",
      downloaded: 10 * TB,
      privilege: `得到十个邀请名额。`,
    },
    {
      id: 100,
      groupType: "vip",
      name: "贵宾(VIP)",
      privilege: `和Nexus Master拥有相同权限并被认为是精英成员。免除自动降级`,
    },
    {
      id: 200,
      groupType: "manager",
      name: "养老族(Retiree)",
      privilege: `退休后的管理组成员。`,
    },
    {
      id: 201,
      groupType: "manager",
      name: "发布员(Uploader)",
      privilege: `专注的发布者。免除自动降级；可以查看匿名用户的真实身份。`,
    },
    {
      id: 202,
      groupType: "manager",
      name: "总版主(Moderator)",
      privilege: `可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。不能管理友情链接、最近消息、论坛版块；不能将种子设为置顶或促销；不能查看用户IP或Email等机密信息；不能删除账号。`,
    },
    {
      id: 203,
      groupType: "manager",
      name: "管理员(Administrator)",
      privilege: `除了不能改变站点设定、管理捐赠外，可以做任何事。`,
    },
    {
      id: 204,
      groupType: "manager",
      name: "维护开发员(Sysop)",
      privilege: `网站开发/维护人员，可以改变站点设定，不能管理捐赠。`,
    },
    {
      id: 205,
      groupType: "manager",
      name: "主管(Staff Leader)",
      privilege: `网站主管，可以做任何事。`,
    },
  ],
  category: [
    {
      name: "分类",
      key: "cat",
      cross: { mode: "append" },
      options: [
        { name: "电影", value: 401 },
        { name: "电视剧", value: 402 },
        { name: "纪录片", value: 404 },
        { name: "音乐", value: 408 },
        { name: "短剧", value: 421 },
        { name: "动漫", value: 405 },
        { name: "学习", value: 419 },
        { name: "体育", value: 407 },
        { name: "MV", value: 406 },
        { name: "软件", value: 411 },
        { name: "游戏", value: 412 },
        { name: "电子书", value: 413 },
        { name: "其他", value: 409 },
        { name: "综艺", value: 420 },
      ],
    },
    {
      name: "年代",
      key: "processing",
      cross: { mode: "append" },
      options: [
        { name: "2025", value: 11 },
        { name: "2024", value: 10 },
        { name: "2023", value: 1 },
        { name: "2022", value: 2 },
        { name: "2021", value: 3 },
        { name: "2020", value: 4 },
        { name: "2019", value: 5 },
        { name: "2018", value: 6 },
        { name: "2017", value: 7 },
        { name: "2016", value: 8 },
        { name: "Earlier/更早", value: 9 },
      ],
    },
    {
      name: "媒介",
      key: "medium",
      cross: { mode: "append" },
      options: [
        { name: "UHD Blu-ray", value: 24 },
        { name: "Blu-ray(原盘)", value: 25 },
        { name: "DVD(原盘)", value: 27 },
        { name: "HDTV", value: 28 },
        { name: "Encode", value: 29 },
        { name: "REMUX", value: 30 },
        { name: "WEB-DL", value: 31 },
        { name: "Track", value: 32 },
        { name: "CD", value: 33 },
        { name: "Other", value: 34 },
      ],
    },
    {
      name: "视频编码",
      key: "codec",
      cross: { mode: "append" },
      options: [
        { name: "H.265/HEVC", value: 6 },
        { name: "H.264/AVC", value: 1 },
        { name: "VC-1", value: 2 },
        { name: "Xvid", value: 3 },
        { name: "MPEG-2/MPEG-4", value: 4 },
        { name: "AV1", value: 7 },
        { name: "Other", value: 5 },
      ],
    },
    {
      name: "音频编码",
      key: "audiocodec",
      cross: { mode: "append" },
      options: [
        { name: "DTS-HD MA", value: 8 },
        { name: "DTS:X", value: 16 },
        { name: "DTS-HD HR", value: 19 },
        { name: "DTS", value: 3 },
        { name: "TrueHD", value: 9 },
        { name: "TrueHD Atmos", value: 15 },
        { name: "DD/AC3", value: 11 },
        { name: "DDP/E-AC3", value: 17 },
        { name: "AAC", value: 6 },
        { name: "LPCM", value: 10 },
        { name: "APE", value: 12 },
        { name: "WAV", value: 13 },
        { name: "M4A", value: 14 },
        { name: "MPEG", value: 18 },
        { name: "FLAC", value: 1 },
        { name: "MP3", value: 4 },
        { name: "Opus", value: 20 },
        { name: "Other", value: 7 },
      ],
    },
    {
      name: "分辨率",
      key: "standard",
      cross: { mode: "append" },
      options: [
        { name: "8K/4320p/4320i", value: 7 },
        { name: "4K/2160p/2160i", value: 6 },
        { name: "1080p/1080i", value: 1 },
        { name: "720p/720i", value: 3 },
        { name: "480p/480i", value: 8 },
        { name: "Other", value: 9 },
      ],
    },
    {
      name: "地区",
      key: "source",
      cross: { mode: "append" },
      options: [
        { name: "CN/中国", value: 15 },
        { name: "HK/香港", value: 16 },
        { name: "TW/台湾", value: 17 },
        { name: "US/美国", value: 18 },
        { name: "EU/欧洲", value: 28 },
        { name: "JPN/日本", value: 19 },
        { name: "Kr/韩国", value: 20 },
        { name: "GB/英国", value: 21 },
        { name: "FR/法国", value: 22 },
        { name: "DE/德国", value: 23 },
        { name: "IN/印度", value: 25 },
        { name: "RU/俄罗斯", value: 30 },
        { name: "CA/加拿大", value: 31 },
        { name: "BR/巴西", value: 32 },
        { name: "SE/瑞典", value: 33 },
        { name: "DK/丹麦", value: 34 },
        { name: "TH/泰国", value: 35 },
        { name: "Other/其他", value: 14 },
      ],
    },
    {
      name: "制作组",
      key: "team",
      cross: { mode: "append" },
      options: [
        { name: "HDK", value: 6 },
        { name: "HDKWeb", value: 7 },
        { name: "HDKGame", value: 8 },
        { name: "Kylin", value: 12 },
        { name: "CatEDU", value: 10 },
        { name: "GodDramas", value: 9 },
        { name: "StarfallWeb", value: 13 },
        { name: "Other", value: 5 },
      ],
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
    {
      name: "审核状态：",
      key: "approval_status",
      options: [
        { value: "", name: "全部" },
        { value: 0, name: "未审" },
        { value: 1, name: "通过" },
        { value: 2, name: "拒绝" },
      ],
      cross: false,
    },
  ],
};
