import type { ISiteMetadata } from "../types";

export const siteMetadata: ISiteMetadata = {
  version: 1,
  id: "hspt",
  name: "回声PT",
  description: "近来可好？",
  tags: ["综合", "影视"],
  collaborator: ["liuyunfz"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://ufcg.pyho/"],

  isDead: true,

  levelRequirements: [
    {
      id: 1,
      name: "(回音者) 𝑷𝒐𝒘𝒆𝒓 𝑼𝒔𝒆𝒓",
      interval: "P1W",
      downloaded: "10GB",
      ratio: 1.1,
      seedingBonus: 40000,
      privilege: "得到一个邀请名额",
    },
    {
      id: 2,
      name: "(共鸣者) 𝑹𝒆𝒔𝒐𝒏𝒂𝒏𝒄𝒆",
      interval: "P1W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 80000,
      privilege: "",
    },
    {
      id: 3,
      name: "(和谐者) 𝑯𝒂𝒓𝒎𝒐𝒏𝒚",
      interval: "P4W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 150000,
      privilege: "得到两个邀请名额",
    },
    {
      id: 4,
      name: "(回荡者) ʀᴇᴠᴇʀʙᴇʀᴀᴛɪᴏɴ",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 250000,
      privilege: "",
    },
    {
      id: 5,
      name: "(雷鸣者) ᴛʜᴜɴᴅᴇʀ",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 400000,
      privilege: "得到三个邀请名额",
    },
    {
      id: 6,
      name: "(巅峰者) Ⱥᵽɇx",
      interval: "P60W",
      downloaded: "1024GB",
      ratio: 3.55,
      seedingBonus: 600000,
      privilege: "",
    },
    {
      id: 7,
      name: "(传承者) ʟᴇɢᴀᴄy",
      interval: "P80W",
      downloaded: "1536GB",
      ratio: 4.05,
      seedingBonus: 800000,
      privilege: "得到五个邀请名额",
    },
    {
      id: 8,
      name: "(永恒者) 𝕰𝖙𝖊𝖗𝖓𝖎𝖙𝖞",
      interval: "P100W",
      downloaded: "3072GB",
      ratio: 4.55,
      seedingBonus: 1000000,
      privilege: "得到十个邀请名额",
    },
  ],
};
