import type { ISiteMetadata } from "../types";
import NexusPHP, {
  CategoryInclbookmarked,
  CategoryIncldead,
  CategorySpstate,
  SchemaMetadata,
} from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,

  id: "ilolicon",
  name: "ilolicon",
  aka: ["爱萝莉"],
  description: "主打动漫，追番和萝莉资源，兼顾热门国漫和爆款剧集的连载，设有影视对比区和专业级画质对比bbcode的站点。",
  tags: ["萝莉", "动漫", "成人", "综合", "影视"],
  timezoneOffset: "+0800",

  type: "private",
  schema: "NexusPHP",

  collaborator: ["haowenwu", "anonymous"],

  urls: ["uggcf://zhn.kybyv.pp/"],

  category: [
    {
      name: "搜索入口",
      key: "#url",
      options: [
        { name: "种子区", value: "/torrents.php" },
        { name: "特别区", value: "/special.php" },
      ],
    },
    {
      name: "分类（种子区）",
      key: "cat_torrents",
      notes: "请先设置搜索入口为“种子区”！请勿与特别区类别同时选择！",
      options: [
        { name: "电影 (Movie)", value: 401 },
        { name: "电视剧(TV Series)", value: 402 },
        { name: "纪录片 (Documentary)", value: 404 },
        { name: "动画 (Animation)", value: 405 },
        { name: "音乐 (Music)", value: 408 },
        { name: "舞台演出 (Stage Performance)", value: 410 },
        { name: "漫画/CG杂图/动漫杂志", value: 411 },
        { name: "游戏 (Game)", value: 412 },
        { name: "软件 (Software)", value: 413 },
        { name: "综艺(TV Show)", value: 430 },
      ],
      cross: { mode: "append", key: "cat" },
    },
    {
      name: "分类（特别区）",
      key: "cat_special",
      notes: "请先设置搜索入口为“特别区”！请勿与种子区类别同时选择！",
      options: [
        { name: "写真(Picture)", value: 418 },
        { name: "AV(无码/Uncensored)", value: 419 },
        { name: "AV(有码/Censored)", value: 420 },
        { name: "里番(Hentai)", value: 421 },
        { name: "H-综艺(H TV Show)", value: 422 },
        { name: "里番(Hanime)", value: 423 },
        { name: "H-漫画(H Manga)", value: 424 },
        { name: "H-2D同人动画(H 2D doujin anime)", value: 425 },
        { name: "H-3D同人动画(H 3D doujin anime)", value: 426 },
        { name: "H-CG杂图(H-CG)", value: 427 },
        { name: "H-游戏(H Game)", value: 428 },
        { name: "音声(Audio)", value: 429 },
      ],
      cross: { mode: "append", key: "cat" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "Blu-ray", value: 1 },
        { name: "DVD", value: 2 },
        { name: "Remux", value: 4 },
        { name: "HDTV", value: 5 },
        { name: "Encode", value: 7 },
        { name: "CD", value: 8 },
        { name: "Other", value: 11 },
        { name: "WEB-DL", value: 12 },
        { name: "UHD Blu-ray", value: 14 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "Other", value: 5 },
        { name: "HEVC/x265", value: 8 },
        { name: "AVC/x264", value: 9 },
        { name: "VC-1", value: 12 },
        { name: "MPEG-2", value: 13 },
        { name: "AV1", value: 15 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "FLAC", value: 1 },
        { name: "DTS", value: 3 },
        { name: "AAC", value: 6 },
        { name: "TrueHD", value: 9 },
        { name: "DTS-HD MA", value: 10 },
        { name: "AC3/DD", value: 13 },
        { name: "Other", value: 14 },
        { name: "LPCM", value: 15 },
        { name: "DDP/E-AC3", value: 20 },
        { name: "MP3", value: 21 },
        { name: "DTS:X", value: 23 },
        { name: "OPUS", value: 24 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "1080p", value: 1 },
        { name: "1080i", value: 2 },
        { name: "720p", value: 3 },
        { name: "SD", value: 4 },
        { name: "2160p/4K", value: 5 },
        { name: "Other", value: 9 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "Other", value: 5 },
        { name: "VCB-Studio", value: 11 },
        { name: "7³ACG", value: 15 },
        { name: "Snow-Raws", value: 39 },
        { name: "jsum@U2", value: 40 },
        { name: "GodDramas", value: 41 },
        { name: "AI-Raws", value: 42 },
        { name: "CMCT", value: 46 },
        { name: "beAst", value: 47 },
        { name: "ANK-Raws", value: 48 },
        { name: "LittleBakas!", value: 49 },
        { name: "mawen1250", value: 50 },
        { name: "Moozzi2", value: 53 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "地区",
      key: "source",
      options: [
        { name: "大陆 (CHN)", value: 1 },
        { name: "香港 (HKG)", value: 2 },
        { name: "台湾 (TWN)", value: 3 },
        { name: "欧美 (West)", value: 4 },
        { name: "韩国 (KOR)", value: 5 },
        { name: "日本 (JPN)", value: 6 },
        { name: "印度 (IND)", value: 7 },
        { name: "俄国 (RUS)", value: 8 },
        { name: "泰国 (THA)", value: 11 },
        { name: "其它 (Other)", value: 13 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "标签",
      key: "tag_id",
      options: [
        { name: "禁转", value: 1 },
        { name: "首发", value: 2 },
        { name: "官方", value: 3 },
        { name: "DIY", value: 4 },
        { name: "国语", value: 5 },
        { name: "中字", value: 6 },
        { name: "HDR10", value: 7 },
        { name: "R18", value: 8 },
        { name: "原生原盘", value: 9 },
        { name: "其他", value: 10 },
        { name: "LOLI", value: 11 },
        { name: "DoVi", value: 13 },
        { name: "HDR10+", value: 14 },
        { name: "自购", value: 15 },
        { name: "Atmos", value: 16 },
        { name: "零魔", value: 17 },
        { name: "ENSub", value: 18 },
        { name: "GalGame", value: 19 },
        { name: "原创", value: 20 },
        { name: "分集", value: 21 },
        { name: "特效", value: 22 },
        { name: "粤语", value: 23 },
        { name: "无对白", value: 24 },
        { name: "精选", value: 25 },
      ],
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  searchEntry: {
    area_torrents: { name: "种子区", requestConfig: { url: "/torrents.php" } },
    area_special: { name: "特别区", requestConfig: { url: "/special.php" } },
  },

  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      id: {
        selector: ["a[href*='userdetails.php'][class*='Name']:first", "a[href*='userdetails.php']:first"],
        attr: "href",
        filters: [{ name: "querystring", args: ["uuid"] }],
      },
    },
    process: [
      {
        requestConfig: { url: "/index.php", responseType: "document" },
        fields: ["id", "name"],
      },
      {
        requestConfig: { url: "/userdetails.php", responseType: "document" },
        assertion: { id: "params.uuid" },
        fields: [
          "messageCount",
          "uploaded",
          "trueUploaded",
          "downloaded",
          "trueDownloaded",
          "levelName",
          "bonus",
          "seedingBonus",
          "joinTime",
          "seeding",
          "seedingSize",
          "hnrUnsatisfied",
          "hnrPreWarning",
        ],
      },
      {
        requestConfig: { url: "/mybonus.php", responseType: "document" },
        fields: ["bonusPerHour"],
      },
    ],
  },
  levelRequirements: [
    {
      id: 1,
      groupType: "user",
      name: "平民",
      privilege:
        "被降级的用户，他们有14天时间来提升分享率，否则他们会被踢。可以上传字幕。可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 2,
      groupType: "user",
      name: "初级魔法少女",
      privilege: "新用户的默认级别。可以更新过期的外部信息，如IMDb信息。",
    },
    {
      id: 3,
      groupType: "user",
      name: "有点经验的魔法少女",
      seedingBonus: 50000,
      ratio: 1.05,
      interval: "P5W",
      downloaded: "50GB",
      privilege: "可以发布趣味盒内容。",
    },
    {
      id: 4,
      groupType: "user",
      name: "高级魔法少女",
      seedingBonus: 200000,
      ratio: 1.55,
      interval: "P8W",
      downloaded: "120GB",
      privilege: "权限同 Power User。",
    },
    {
      id: 5,
      groupType: "user",
      name: "疯狂魔法少女",
      seedingBonus: 400000,
      ratio: 2.05,
      interval: "P15W",
      downloaded: "300GB",
      privilege: "Crazy User及以上用户封存账号后不会被删除。",
    },
    {
      id: 6,
      groupType: "user",
      name: "超级疯狂的魔法少女",
      seedingBonus: 688888,
      ratio: 2.55,
      interval: "P25W",
      downloaded: "500GB",
      privilege: "权限同 Crazy User。",
    },
    {
      id: 7,
      groupType: "user",
      name: "经验丰富的魔法少女",
      seedingBonus: 1011000,
      ratio: 3.05,
      interval: "P40W",
      downloaded: "750GB",
      privilege: "Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 8,
      groupType: "user",
      name: "极限魔法少女",
      seedingBonus: 1500000,
      ratio: 3.55,
      interval: "P60W",
      downloaded: "1TB",
      privilege: "允许使用个性条；可以查看NFO文档。",
    },
    {
      id: 9,
      groupType: "user",
      name: "终极魔法少女",
      seedingBonus: 2000000,
      ratio: 4.05,
      interval: "P80W",
      downloaded: "1.5TB",
      privilege: "可以请求续种；得到一个邀请名额。",
    },
    {
      id: 10,
      groupType: "user",
      name: "尼克斯大师",
      seedingBonus: 3000000,
      ratio: 4.55,
      interval: "P100W",
      downloaded: "3TB",
      privilege: "可以查看种子结构；得到两个邀请名额。",
    },
    {
      id: 100,
      groupType: "vip",
      name: "贵宾",
      privilege: "和Nexus Master拥有相同权限并被认为是精英成员。免除自动降级。VIP下载不计算下载量。",
    },
    {
      id: 200,
      groupType: "manager",
      name: "退休的魔法少女",
      privilege: "退休后的管理组成员。",
    },
    {
      id: 201,
      groupType: "manager",
      name: "魔法释放者",
      privilege: "专注的发布者。免除自动降级；",
    },
    {
      id: 202,
      groupType: "manager",
      name: "至高的魔法师",
      privilege:
        "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。不能管理友情链接、最近消息、论坛版块；不能将种子设为置顶或促销；不能查看用户IP或Email等机密信息；不能删除账号。",
    },
    {
      id: 203,
      groupType: "manager",
      name: "顶级魔法少女",
      privilege: "除了不能改变站点设定、管理捐赠外，可以做任何事。",
    },
    {
      id: 204,
      groupType: "manager",
      name: "维护魔法少女",
      privilege: "网站开发/维护人员，可以改变站点设定，不能管理捐赠。",
    },
    {
      id: 205,
      groupType: "manager",
      name: "首席魔法少女",
      privilege: "网站主管，可以做任何事。",
    },
  ],
};

export default class ilolicon extends NexusPHP {
  protected override async requestUserSeedingPage(userId: number, type: string = "seeding"): Promise<string | null> {
    const { data } = await this.request<string>({
      url: "/getusertorrentlistajax.php",
      params: { useruuid: userId, type },
    });
    return data || null;
  }
}
