import type { ISiteMetadata } from "../types";
import {
  CategoryInclbookmarked,
  CategoryIncldead,
  CategorySpstate,
  SchemaMetadata,
  xiaomloveDefaultUserLevelRequirements,
} from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "kamept",
  name: "KamePT",
  aka: ["龟站"],
  schema: "NexusPHP",
  type: "private",
  urls: ["https://kamept.com/"],
  description: "主打二次元同人AV的站点",
  tags: ["成人", "COS", "动漫", "音乐", "影视"],
  collaborator: ["NekoCH"],

  category: [
    {
      name: "搜索入口",
      key: "#url",
      options: [
        { name: "种子区", value: "/torrents.php" },
        { name: "特别区", value: "/special.php" },
      ],
    },
    {
      name: "分类（种子区）",
      key: "cat_torrents",
      notes: "请先设置搜索入口为“种子区”！请勿与特别区类别同时选择！",
      options: [
        { name: "同人AV", value: 410 },
        { name: "男娘", value: 413 },
        { name: "VR同人", value: 414 },
        { name: "Cosplay套图", value: 417 },
        { name: "里番", value: 419 },
        { name: "2D动画", value: 411 },
        { name: "3D动画", value: 423 },
        { name: "画师CG", value: 433 },
        { name: "同人志", value: 435 },
        { name: "单行本", value: 424 },
        { name: "游戏", value: 415 },
        { name: "中文游戏", value: 418 },
        { name: "游戏CG", value: 434 },
        { name: "音乐", value: 437 },
        { name: "外语音声", value: 420 },
        { name: "中文音声", value: 421 },
        { name: "视频音声", value: 422 },
      ],
      cross: { mode: "append", key: "cat" },
    },
    {
      name: "分类（特别区）",
      key: "cat_special",
      notes: "请先设置搜索入口为“特别区”！请勿与种子区类别同时选择！",
      options: [
        { name: "动画", value: 425 },
        { name: "电影", value: 426 },
        { name: "电视剧", value: 427 },
        { name: "视频", value: 429 },
        { name: "书籍", value: 430 },
        { name: "软件", value: 431 },
        { name: "卡组", value: 432 },
        { name: "模型", value: 436 },
      ],
      cross: { mode: "append", key: "cat" },
    },
    {
      name: "马赛克",
      key: "source",
      options: [
        { name: "全身无码", value: 1 },
        { name: "下体无码", value: 2 },
        { name: "脸部无码", value: 3 },
        { name: "全身有码", value: 4 },
        { name: "不漏点软色情", value: 7 },
        { name: "Other", value: 6 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "中文字幕",
      key: "team",
      options: [{ name: "中文字幕", value: 1 }],
      cross: { mode: "append" },
    },
    {
      name: "原始语言",
      key: "medium",
      options: [
        { name: "中文", value: 1 },
        { name: "粤语", value: 12 },
        { name: "日语（日本語）", value: 2 },
        { name: "俄语（Россия）", value: 3 },
        { name: "德语（Deutsch）", value: 7 },
        { name: "英语（English）", value: 4 },
        { name: "意大利语（Italiano）", value: 5 },
        { name: "西班牙语（Español）", value: 6 },
        { name: "韩语（한국어）", value: 11 },
        { name: "印尼语（Bahasa Indonesia）", value: 9 },
        { name: "印地语（हिन्दी）", value: 10 },
        { name: "法语（français）", value: 8 },
        { name: "其他（other）", value: 13 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "处理",
      key: "processing",
      options: [
        { name: "同人", value: 2 },
        { name: "官方", value: 1 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "标签",
      key: "tag_id",
      options: [
        { name: "原盘", value: 14 },
        { name: "中文字幕", value: 8 },
        { name: "禁转", value: 1 },
        { name: "自购", value: 2 },
        { name: "合集", value: 6 },
        { name: "新作", value: 7 },
        { name: "非原档", value: 17 },
        { name: "不漏点软色情", value: 16 },
        { name: "有水印", value: 15 },
        { name: "全身有码", value: 13 },
        { name: "脸部无码", value: 12 },
        { name: "下身无码", value: 11 },
        { name: "全身无码", value: 10 },
        { name: "口罩/面具等", value: 9 },
      ],
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  searchEntry: {
    area_torrents: { name: "种子区", requestConfig: { url: "/torrents.php" } },
    area_special: { name: "特别区", requestConfig: { url: "/special.php" } },
  },

  levelRequirements: [...xiaomloveDefaultUserLevelRequirements],
};
