import { type ISiteMetadata } from "../types";
import { SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,
  id: "march",
  name: "March-Media",
  aka: ["三月传媒"],
  description: "分享所爱，开放交流", // 站点说明
  tags: ["WEB", "综合"],
  timezoneOffset: "+0800",
  type: "private",
  schema: "NexusPHP",
  urls: ["https://duckboobee.org/", "https://marchcms.org/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "Movies/电影", value: 401 },
        { name: "TV Series/电视剧", value: 402 },
        { name: "TV Shows/综艺", value: 403 },
        { name: "Documentaries/记录片", value: 404 },
        { name: "Animations/动漫、动画", value: 405 },
        { name: "MV/演唱会", value: 406 },
        { name: "Sports/体育", value: 407 },
        { name: "Music/音乐", value: 408 },
        { name: "Others/其他", value: 409 },
      ],
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "WEB-DL", value: 13 },
        { name: "DVD", value: 8 },
        { name: "HDTV", value: 5 },
        { name: "Other", value: 4 },
        { name: "Encode", value: 7 },
        { name: "Remux", value: 3 },
        { name: "DVDR", value: 2 },
        { name: "Blu-Ray", value: 1 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "H.264", value: 1 },
        { name: "HEVC", value: 2 },
        { name: "H.265", value: 3 },
        { name: "MPEG-2", value: 4 },
        { name: "MPEG-4", value: 5 },
        { name: "X.264", value: 6 },
        { name: "X.265", value: 7 },
        { name: "XVID", value: 9 },
        { name: "AV1", value: 10 },
        { name: "Other", value: 11 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "1080p", value: 1 },
        { name: "1080i", value: 2 },
        { name: "720p", value: 3 },
        { name: "576P", value: 4 },
        { name: "2160P", value: 6 },
        { name: "480P", value: 7 },
        { name: "4320P", value: 8 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "3MWEB", value: 1 },
        { name: "CHD", value: 2 },
        { name: "TTG", value: 3 },
        { name: "CMCT", value: 4 },
        { name: "HDSKY", value: 5 },
        { name: "OurBits", value: 6 },
        { name: "M-Team", value: 7 },
        { name: "WIKI", value: 8 },
        { name: "Beast", value: 9 },
        { name: "HHWEB", value: 10 },
        { name: "Other", value: 11 },
      ],
      cross: { mode: "append" },
    },
  ],

  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      bonus: {
        selector: ["td.rowhead:contains('魔力值') + td, td.rowhead:contains('Karma Points') + td"],
        filters: [{ name: "parseNumber" }],
      },
    },
  },
  levelRequirements: [
    {
      id: 1,
      name: "Peasant",
      privilege:
        "被降级的用户，他们有30天时间来提升分享率，否则他们会被踢。不能发表趣味盒内容；不能申请友情链接；不能上传字幕。",
    },
    {
      id: 2,
      name: "User",
      privilege: "新用户的默认级别。只能在每周六中午12点至每周日晚上11点59分发布种子。",
    },
    {
      id: 3,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      privilege: '得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 4,
      name: "Elite User",
      interval: "P4W",
      downloaded: "120GB",
      ratio: 1.55,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 5,
      name: "Crazy User",
      interval: "P8W",
      downloaded: "300GB",
      ratio: 2.05,
      privilege: "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 6,
      name: "Insane User",
      interval: "P15W",
      downloaded: "500GB",
      ratio: 2.55,
      privilege: "可以查看普通日志。",
    },
    {
      id: 7,
      name: "Veteran User",
      interval: "P25W",
      downloaded: "1024GB",
      ratio: 3.05,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 8,
      name: "Extreme User",
      interval: "P40W",
      downloaded: "1TB",
      ratio: 3.55,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 9,
      name: "Ultimate User",
      interval: "P60W",
      downloaded: "1.5TB",
      ratio: 4.05,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 10,
      name: "Nexus Master",
      interval: "P80W",
      downloaded: "4TB",
      ratio: 5.05,
      privilege: "得到十个邀请名额。",
    },
    {
      id: 100,
      groupType: "vip",
      name: "贵宾(VIP)",
      privilege: "和Nexus Master拥有相同权限并被认为是精英成员。免除自动降级。",
    },
    {
      id: 200,
      groupType: "manager",
      name: "养老族(Retiree)",
      privilege: "退休后的管理组成员。",
    },
    {
      id: 201,
      groupType: "manager",
      name: "发布员(Uploader)",
      privilege: "专注的发布者。免除自动降级；可以查看匿名用户的真实身份。",
    },
    {
      id: 202,
      groupType: "manager",
      name: "总版主(Moderator)",
      privilege:
        "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。不能管理友情链接、最近消息、论坛版块；不能将种子设为置顶或促销；不能查看用户IP或Email等机密信息；不能删除账号。",
    },
    {
      id: 203,
      groupType: "manager",
      name: "管理员(Administrator)",
      privilege: "除了不能改变站点设定、管理捐赠外，可以做任何事。",
    },
    {
      id: 204,
      groupType: "manager",
      name: "维护开发员(Sysop)",
      privilege: "网站开发/维护人员，可以改变站点设定，不能管理捐赠。",
    },
    {
      id: 205,
      groupType: "manager",
      name: "主管(Staff Leader)",
      privilege: "网站主管，可以做任何事。",
    },
  ],
};
