import { type ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "ptchina",
  name: "PTChina",
  aka: ["铂金学院"],
  description: "PT新手的梦想之家，PT老鸟的黄埔军校",
  timezoneOffset: "+0800",

  collaborator: ["zzhhxx"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://cgpuvan.bet/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "电影/Movies", value: 401 },
        { name: "电视剧/TV-Series", value: 402 },
        { name: "纪录片/Documentary", value: 404 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "UHD原盘", value: 1 },
        { name: "UHD DIY", value: 2 },
        { name: "UHD Remux", value: 3 },
        { name: "UHD 压制", value: 4 },
        { name: "BD 原盘", value: 5 },
        { name: "BD DIY", value: 6 },
        { name: "BD Remux", value: 7 },
        { name: "1080p/i压制", value: 8 },
        { name: "WEB-DL", value: 9 },
        { name: "HDTV", value: 12 },
        { name: "Other", value: 13 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "H.264/AVC", value: 1 },
        { name: "x264", value: 2 },
        { name: "H.265/HEVC", value: 3 },
        { name: "X265", value: 4 },
        { name: "VC-1", value: 5 },
        { name: "MPEG-2", value: 11 },
        { name: "Xvid", value: 13 },
        { name: "MPEG-4", value: 12 },
        { name: "AV1", value: 14 },
        { name: "Other", value: 15 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "TrueHD Atmos", value: 1 },
        { name: "DTS", value: 2 },
        { name: "DTS X", value: 3 },
        { name: "DTS-HDMA", value: 4 },
        { name: "DTS-HD HR", value: 5 },
        { name: "True-HD", value: 6 },
        { name: "LPCM", value: 7 },
        { name: "DDP Atmos", value: 15 },
        { name: "DDP/DD+/EAC3", value: 16 },
        { name: "DDP/DD+", value: 17 },
        { name: "AC3", value: 18 },
        { name: "AAC", value: 19 },
        { name: "FLAC", value: 20 },
        { name: "APE", value: 21 },
        { name: "WAV", value: 22 },
        { name: "MP3", value: 23 },
        { name: "Other", value: 24 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "4K/UHD/2160P", value: 1 },
        { name: "2K/1440p", value: 2 },
        { name: "1080p", value: 3 },
        { name: "1080i", value: 4 },
        { name: "Other", value: 6 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "PTChina", value: 1 },
        { name: "CHD/CHDBits", value: 2 },
        { name: "HDC/HDChina", value: 3 },
        { name: "TTG", value: 4 },
        { name: "WiKi", value: 5 },
        { name: "beAst", value: 21 },
        { name: "CMCT", value: 22 },
        { name: "FRDS", value: 23 },
        { name: "HDS/HDSky", value: 24 },
        { name: "OurBits", value: 25 },
        { name: "PTer", value: 26 },
        { name: "LemonHD", value: 27 },
        { name: "HDHome", value: 28 },
        { name: "PTHome", value: 29 },
        { name: "Audiences", value: 30 },
        { name: "Hares", value: 31 },
        { name: "BTN/NTb", value: 32 },
        { name: "EPSiLON", value: 33 },
        { name: "FraMeSToR", value: 34 },
        { name: "Other", value: 35 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别。只能在每周六中午12点至每周日晚上11点59分发布种子。",
    },
    {
      id: 1,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 40000,
      privilege:
        '得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 2,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 80000,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 150000,
      privilege: "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 250000,
      privilege: "可以查看普通日志。",
    },
    {
      id: 5,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 400000,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 3.55,
      seedingBonus: 600000,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 7,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 4.05,
      seedingBonus: 800000,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 8,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 4.55,
      seedingBonus: 1000000,
      privilege: "得到十个邀请名额。",
    },
  ],
};
