import type { ISiteMetadata } from "../types";
import { SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "ptsbao",
  name: "PTSBao",
  aka: ["烧包", "骚包"],
  description: "烧包 - 扬帆远航 风雨同路",
  tags: ["影视", "综合"],
  collaborator: ["laizony", "ted423", "zxb0303"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://cgfonb.pyho/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { value: 424, name: "限制" },
        { value: 409, name: "其他" },
        { value: 423, name: "原创" },
        { value: 404, name: "纪录片" },
        { value: 414, name: "音乐" },
        { value: 405, name: "动漫" },
        { value: 403, name: "综艺" },
        { value: 402, name: "剧集" },
        { value: 401, name: "电影" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "来源",
      key: "source",
      options: [
        { value: 39, name: "纪录片-BBC" },
        { value: 89, name: "电影-标清" },
        { value: 94, name: "电影-HDTV" },
        { value: 87, name: "其它" },
        { value: 49, name: "音乐-其他" },
        { value: 70, name: "剧集-其他" },
        { value: 86, name: "写真" },
        { value: 88, name: "电影-Remux" },
        { value: 90, name: "剧集-英剧" },
        { value: 41, name: "纪录片-其他" },
        { value: 9, name: "音乐-古典" },
        { value: 47, name: "动漫-其他" },
        { value: 4, name: "电影-WEB-DL" },
        { value: 84, name: "H漫画" },
        { value: 75, name: "其他" },
        { value: 31, name: "期刊书籍" },
        { value: 26, name: "剧集-日剧" },
        { value: 40, name: "纪录片-历史频道" },
        { value: 76, name: "动漫-音乐" },
        { value: 44, name: "软件-其他" },
        { value: 85, name: "H动漫" },
        { value: 17, name: "综艺-科教" },
        { value: 93, name: "电影-DIY" },
        { value: 8, name: "音乐-日韩" },
        { value: 1, name: "音乐-欧美" },
        { value: 73, name: "晚会活动视频" },
        { value: 43, name: "软件-手机" },
        { value: 46, name: "动漫-漫画" },
        { value: 55, name: "电影-原盘" },
        { value: 35, name: "纪录片-探索频道" },
        { value: 30, name: "讲座演讲" },
        { value: 24, name: "剧集-港台" },
        { value: 83, name: "禁片-原盘" },
        { value: 22, name: "体育-其他" },
        { value: 19, name: "综艺-典礼" },
        { value: 13, name: "游戏-其他" },
        { value: 77, name: "纪录片-NHK" },
        { value: 78, name: "体育-教学" },
        { value: 82, name: "禁片-高清" },
        { value: 68, name: "其他-其他视频" },
        { value: 67, name: "动漫-OVA剧场版" },
        { value: 59, name: "MV-合集" },
        { value: 58, name: "考研资料" },
        { value: 2, name: "音乐-华语" },
        { value: 54, name: "个人整理合集" },
        { value: 52, name: "游戏-掌机" },
        { value: 16, name: "综艺-晚会" },
        { value: 50, name: "软件-Linux" },
        { value: 27, name: "剧集-韩剧" },
        { value: 56, name: "个人录制视频" },
        { value: 91, name: "电影-720" },
        { value: 12, name: "游戏-网络" },
        { value: 18, name: "综艺-娱乐" },
        { value: 21, name: "体育-足球" },
        { value: 25, name: "剧集-美剧" },
        { value: 81, name: "成人-有码" },
        { value: 79, name: "软件-Mac" },
        { value: 29, name: "专业学科" },
        { value: 37, name: "纪录片-CCTV" },
        { value: 51, name: "MV-单集" },
        { value: 45, name: "动漫-连载" },
        { value: 65, name: "音乐-原声" },
        { value: 63, name: "其他-电子文档" },
        { value: 32, name: "外语学习" },
        { value: 3, name: "电影-1080" },
        { value: 10, name: "音乐-无损" },
        { value: 11, name: "游戏-单机" },
        { value: 60, name: "MV-演唱会" },
        { value: 15, name: "综艺-综合" },
        { value: 62, name: "其他-游戏视频" },
        { value: 20, name: "体育-篮球" },
        { value: 23, name: "剧集-大陆" },
        { value: 66, name: "动漫-完结" },
        { value: 80, name: "成人-无码" },
        { value: 42, name: "软件-Windows" },
        { value: 71, name: "个人原创作品" },
        { value: 34, name: "纪录片-国家地理" },
        { value: 92, name: "电影-4K" },
        { value: 95, name: "网飞" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { value: 11, name: "AI" },
        { value: 9, name: "其他" },
        { value: 8, name: "CD" },
        { value: 3, name: "DVD" },
        { value: 5, name: "HDTV" },
        { value: 2, name: "WEB-DL" },
        { value: 1, name: "BluRay" },
        { value: 10, name: "UHD" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { value: 5, name: "Other" },
        { value: 8, name: "ProRes" },
        { value: 3, name: "Xvid/DivX" },
        { value: 7, name: "VP9" },
        { value: 4, name: "MPEG-2" },
        { value: 2, name: "VC-1" },
        { value: 1, name: "H.264" },
        { value: 6, name: "H.265" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { value: 7, name: "Other" },
        { value: 15, name: "MP2" },
        { value: 14, name: "OPUS" },
        { value: 13, name: "DTS:X" },
        { value: 12, name: "LPCM/PCM" },
        { value: 5, name: "OGG" },
        { value: 4, name: "MP3" },
        { value: 2, name: "APE" },
        { value: 1, name: "FLAC" },
        { value: 3, name: "DTS" },
        { value: 6, name: "AAC" },
        { value: 11, name: "AC3" },
        { value: 10, name: "DDP/DD+" },
        { value: 9, name: "TrueHD" },
        { value: 8, name: "DTSHD" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { value: 6, name: "Other" },
        { value: 4, name: "480" },
        { value: 3, name: "576" },
        { value: 2, name: "720" },
        { value: 1, name: "1080" },
        { value: 7, name: "2K" },
        { value: 5, name: "4K" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "处理",
      key: "processing",
      options: [
        { value: 6, name: "AI" },
        { value: 3, name: "Other" },
        { value: 5, name: "原盘" },
        { value: 2, name: "重编码" },
        { value: 4, name: "源码" },
        { value: 1, name: "Remux" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { value: 20, name: "SGXT" },
        { value: 19, name: "FFansAIeNcE" },
        { value: 18, name: "QHstudIo" },
        { value: 17, name: "19977" },
        { value: 16, name: "Enichi" },
        { value: 15, name: "FHDMv" },
        { value: 14, name: "FFansDVD" },
        { value: 7, name: "Other" },
        { value: 5, name: "FRDS" },
        { value: 4, name: "CMCT" },
        { value: 2, name: "CHD" },
        { value: 9, name: "HDSky" },
        { value: 3, name: "TTG" },
        { value: 6, name: "HDC" },
        { value: 10, name: "HQC" },
        { value: 13, name: "FFansTV" },
        { value: 12, name: "FFansWEB" },
        { value: 11, name: "OPS" },
        { value: 8, name: "FFansBD" },
      ],
    },
  ],

  levelRequirements: [
    {
      id: 1,
      name: "小主",
      privilege:
        "最低等级，若下载达到50GB需大于0.4分享率，超100GB需大于0.5，超200GB需大于0.6，超400GB需大于0.7，超800GB需大于0.8，否则自动降级至本级。",
    },
    {
      id: 2,
      name: "常在",
      interval: "P1W",
      downloaded: "50GB",
      ratio: 1.05,
      privilege: "符合注册满1周且下载50GB并分享率高于1.05时自动提升，随时低于0.95自动降级。",
    },
    {
      id: 3,
      name: "贵人",
      interval: "P2W",
      downloaded: "150GB",
      ratio: 1.55,
      privilege: "符合注册满2周且下载150GB并分享率高于1.55时自动提升，随时低于1.45自动降级。",
    },
    {
      id: 4,
      name: "嫔",
      interval: "P4W",
      downloaded: "300GB",
      ratio: 2.05,
      privilege: "符合注册满4周且下载300GB并分享率高于2.05时自动提升，随时低于1.95自动降级。",
    },
    {
      id: 5,
      name: "贵嫔",
      interval: "P8W",
      downloaded: "500GB",
      ratio: 2.55,
      privilege: "符合注册满8周且下载500GB并分享率高于2.55时自动提升，随时低于2.45自动降级。",
    },
    {
      id: 6,
      name: "妃",
      interval: "P16W",
      downloaded: "750GB",
      ratio: 3.05,
      privilege: "符合注册满16周且下载750GB并分享率高于3.05时自动提升，随时低于2.95自动降级。",
    },
    {
      id: 7,
      name: "贵妃",
      interval: "P24W",
      downloaded: "1TB",
      ratio: 3.55,
      privilege: "符合注册满24周且下载1TB并分享率高于3.55时自动提升，随时低于3.45自动降级。",
    },
    {
      id: 8,
      name: "皇妃",
      interval: "P36W",
      downloaded: "1.5TB",
      ratio: 4.05,
      privilege: "符合注册满36周且下载1.5TB并分享率高于4.05时自动提升，随时低于3.95自动降级。",
    },
    {
      id: 9,
      name: "皇后",
      interval: "P52W",
      downloaded: "3TB",
      ratio: 4.55,
      privilege: "符合注册满52周且下载3TB并分享率高于4.55时自动提升，随时低于4.45自动降级。为网站捐款也可获得此等级。",
    },
  ],
};
