import type { ISiteMetadata } from "../types";
import { CategoryIncldead, CategorySpstate, CategoryInclbookmarked, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "rousi",
  name: "Rousi",
  aka: ["肉丝"],
  description: "你也喜欢 Rousi 对吧？",
  tags: ["影视", "综合", "成人"],

  collaborator: ["CarlJia"],

  type: "private",
  schema: "NexusPHP",

  urls: ["ROT13:uggcf://ebhfv.mvc/"],
  favicon: "./rousi.ico",

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { value: 401, name: "Movies(电影)" },
        { value: 402, name: "TV Series(电视剧)" },
        { value: 403, name: "TV Shows(综艺)" },
        { value: 407, name: "Sports(体育、竞技、武术及相关)" },
        { value: 404, name: "Documentaries(纪录片)" },
        { value: 410, name: "Games(游戏及相关)" },
        { value: 406, name: "Music(音乐、专辑、MV、演唱会)" },
        { value: 419, name: "Art(舞蹈、歌剧、戏曲、相声、评书等)" },
        { value: 411, name: "Science(科学、知识、技能)" },
        { value: 412, name: "School(应试、考级、初中以上教育)" },
        { value: 413, name: "Book(书籍、杂志、报刊、有声书)" },
        { value: 414, name: "Code(IT技术、建模、编程、信息技术、大数据、人工智能)" },
        { value: 405, name: "Animations(3D动画、2.5次元)" },
        { value: 415, name: "ACGN(二次元、漫画、动漫)" },
        { value: 416, name: "Baby(婴幼、儿童、早教、小学及相关)" },
        { value: 417, name: "Resource(图片、文档、素材、模板)" },
        { value: 418, name: "Software(软件、系统、程序、APP等)" },
        { value: 409, name: "Other(其它，确认上边无分类)" },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
    {
      name: "审核状态：",
      key: "audit",
      options: [
        { value: "", name: "全部" },
        { value: 0, name: "未审" },
        { value: 1, name: "通过" },
        { value: 2, name: "拒绝" },
      ],
      cross: false,
    },
  ],
  search: {
    ...SchemaMetadata.search,
  },
  levelRequirements: [
    {
      id: 1,
      name: "User",
      privilege: "新用户的默认级别",
    },
    {
      id: 2,
      groupType: "user",
      name: "Power User",
      privilege: "首次升级至此等级的用户没有任何邀请名额",
      seedingBonus: 40000,
      ratio: 1.05,
      interval: "P4W",
      downloaded: "50GB",
    },
    {
      id: 3,
      groupType: "user",
      name: "Elite User",
      privilege: "首次升级至此等级的用户将获得1个邀请名额",
      seedingBonus: 80000,
      ratio: 1.55,
      interval: "P8W",
      downloaded: "120GB",
    },
    {
      id: 4,
      groupType: "user",
      name: "Crazy User",
      privilege: "首次升级至此等级的用户将获得2个邀请名额",
      seedingBonus: 1000000,
      ratio: 2.05,
      interval: "P15W",
      downloaded: "1024GB",
    },
    {
      id: 5,
      groupType: "user",
      name: "Insane User",
      privilege: "首次升级至此等级的用户将获得5个邀请名额",
      seedingBonus: 2000000,
      ratio: 2.55,
      interval: "P25W",
      downloaded: "2048GB",
    },
    {
      id: 6,
      groupType: "user",
      name: "Veteran User",
      privilege: "首次升级至此等级的用户将获得10个邀请名额",
      seedingBonus: 3000000,
      ratio: 3.05,
      interval: "P40W",
      downloaded: "5120GB",
    },
    {
      id: 7,
      groupType: "user",
      name: "Extreme User",
      privilege: "首次升级至此等级的用户将获得10个邀请名额",
      seedingBonus: 5000000,
      ratio: 3.55,
      interval: "P60W",
      downloaded: "10240GB",
    },
    {
      id: 8,
      groupType: "user",
      name: "Ultimate User",
      privilege: "首次升级至此等级的用户将获得10个邀请名额",
      seedingBonus: 8000000,
      ratio: 4.05,
      interval: "P80W",
      downloaded: "20480GB",
    },
    {
      id: 9,
      groupType: "user",
      name: "Nexus Master",
      privilege: "首次升级至此等级的用户将获得10个邀请名额",
      seedingBonus: 10000000,
      ratio: 4.55,
      interval: "P100W",
      downloaded: "30720GB",
    },
  ],
};
