import { ISiteMetadata } from "@ptd/site";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  id: "rs",
  version: 1,
  name: "睿思",
  aka: ["西电睿思"],
  description: "西电睿思PT",
  tags: ["教育网", "影视", "综合"],
  timezoneOffset: "+0800",
  collaborator: ["lsy223622"],
  type: "private",
  schema: "NexusPHP",
  urls: ["https://resource.xidian.edu.cn/"],
  favicon: "./_default_nexusphp.png",

  category: [
    {
      name: "类型",
      key: "cat",
      options: [
        { value: "401", name: "电影" },
        { value: "402", name: "电视剧" },
        { value: "403", name: "综艺" },
        { value: "404", name: "纪录片" },
        { value: "405", name: "动漫" },
        { value: "406", name: "MV" },
        { value: "407", name: "体育" },
        { value: "408", name: "音乐" },
        { value: "410", name: "游戏" },
        { value: "411", name: "电子书" },
        { value: "412", name: "软件" },
        { value: "413", name: "学习" },
        { value: "414", name: "演出" },
        { value: "409", name: "其他" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "来源",
      key: "source",
      options: [
        { value: "1", name: "Blu-ray" },
        { value: "2", name: "HD DVD" },
        { value: "3", name: "DVD" },
        { value: "4", name: "HDTV" },
        { value: "5", name: "TV" },
        { value: "6", name: "Other" },
        { value: "7", name: "WEB-DL" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { value: "1", name: "Blu-ray" },
        { value: "10", name: "WEB-DL" },
        { value: "2", name: "HD DVD" },
        { value: "3", name: "Remux" },
        { value: "7", name: "Encode" },
        { value: "4", name: "MiniBD" },
        { value: "5", name: "HDTV" },
        { value: "6", name: "DVDR" },
        { value: "8", name: "CD" },
        { value: "9", name: "Track" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { value: "1", name: "H.264" },
        { value: "2", name: "VC-1" },
        { value: "3", name: "Xvid" },
        { value: "4", name: "MPEG-2" },
        { value: "5", name: "Other" },
        { value: "8", name: "H265" },
        { value: "6", name: "x264" },
        { value: "7", name: "x265" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { value: "1", name: "FLAC" },
        { value: "2", name: "APE" },
        { value: "3", name: "DTS" },
        { value: "4", name: "MP3" },
        { value: "5", name: "OGG" },
        { value: "6", name: "AAC" },
        { value: "7", name: "Other" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { value: "6", name: "4320p" },
        { value: "5", name: "2160p" },
        { value: "1", name: "1080p" },
        { value: "2", name: "1080i" },
        { value: "3", name: "720p" },
        { value: "4", name: "SD" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "处理",
      key: "processing",
      options: [
        { value: "1", name: "Raw" },
        { value: "2", name: "Encode" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { value: "1", name: "HDS" },
        { value: "2", name: "CHD" },
        { value: "3", name: "MySiLU" },
        { value: "4", name: "WiKi" },
        { value: "5", name: "Other" },
        { value: "6", name: "RS" },
        { value: "7", name: "VCB-Studio" },
        { value: "8", name: "jsum" },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别。",
    },
    {
      id: 1,
      name: "Power User",
      downloaded: "50GB",
      seedingBonus: 10000,
      ratio: 1.05,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于0.95，你将自动降级。",
    },
    {
      id: 2,
      name: "Elite User",
      downloaded: "120GB",
      seedingBonus: 40000,
      ratio: 1.55,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于1.45，你将自动降级。",
    },
    {
      id: 3,
      name: "Crazy User",
      downloaded: "300GB",
      seedingBonus: 80000,
      ratio: 2.05,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于1.95，你将自动降级。",
    },
    {
      id: 4,
      name: "Insane User",
      downloaded: "500GB",
      seedingBonus: 100000,
      ratio: 2.55,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.45，你将自动降级。",
    },
    {
      id: 5,
      name: "Veteran User",
      downloaded: "750GB",
      seedingBonus: 200000,
      ratio: 3.05,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.95，你将自动降级。",
    },
    {
      id: 6,
      name: "Extreme User",
      downloaded: "1000GB",
      seedingBonus: 400000,
      ratio: 3.55,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.45，你将自动降级。",
    },
    {
      id: 7,
      name: "Ultimate User",
      downloaded: "1500GB",
      seedingBonus: 800000,
      ratio: 4.05,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.95，你将自动降级。",
    },
    {
      id: 8,
      name: "Nexus Master",
      downloaded: "3000GB",
      seedingBonus: 1000000,
      ratio: 4.55,
      privilege: "当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于4.45，你将自动降级。",
    },
  ],
};
