import { type ISiteMetadata } from "../types";
import { SchemaMetadata } from "../schemas/GazelleJSONAPI.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "sugoimusic",
  name: "SugoiMusic",
  aka: ["SM"],
  description:
    "SugoiMusic is a private tracker focused on Asian music: music, concerts, PVs, variety & drama shows, Blu-ray/DVDs, and pictures.",
  tags: ["音乐", "亚洲音乐"],
  timezoneOffset: "+0800",
  collaborator: ["MewX"],

  type: "private",
  schema: "GazelleJSONAPI",

  urls: ["https://sugoimusic.me/"],

  search: {
    ...SchemaMetadata.search!,
    advanceKeywordParams: {
      imdb: false,
    },
  },

  levelRequirements: [
    {
      id: 1,
      name: "User",
      bonus: 0,
      uploads: 0,
      uploaded: "0B",
      ratio: 0,
      privilege: "Default class; SugoiMusic ;) ; Can access basic Top 10",
    },
    {
      id: 2,
      name: "Member",
      bonus: 1000,
      uploads: 0,
      uploaded: "0B",
      ratio: 0,
      privilege: "Top 10 filters; Make requests; Use torrent notifications system",
    },
    {
      id: 3,
      name: "Merit",
      bonus: 2500,
      uploads: 5,
      uploaded: "0B",
      ratio: 0,
      privilege: "Comment in Suggestions forum; Inactivity-pruning disabled",
    },
    {
      id: 4,
      name: "Power User",
      bonus: 5000,
      uploads: 25,
      uploaded: "1GB",
      ratio: 0,
      privilege:
        "Power User Forum; Batch download torrents; Collage subscriptions; Edit artist/group info; Make new suggestions",
    },
    {
      id: 5,
      name: "Extreme User",
      bonus: 25000,
      uploads: 50,
      uploaded: "5GB",
      ratio: 0,
      privilege: "1 Personal collage; Submit 1 login background; Add/delete own screenshots",
    },
    {
      id: 6,
      name: "Pro User",
      bonus: 100000,
      uploads: 200,
      uploaded: "20GB",
      ratio: 0,
      privilege: "Invite forum; 2 Personal collages; Comment on suggestions/bugs forums",
    },
    {
      id: 7,
      name: "Commandant",
      bonus: 250000,
      uploads: 500,
      uploaded: "50GB",
      ratio: 0,
      privilege: "Search results beyond page 20; 4 Personal collages; Rename own collages",
    },
    {
      id: 8,
      name: "Elite",
      bonus: 500000,
      uploads: 1000,
      uploaded: "200GB",
      ratio: 0,
      privilege: "Elite Forum; 5 Personal collages; Edit any torrent; Add artists to groups",
    },
    {
      id: 9,
      name: "Senior Elite",
      bonus: 750000,
      uploads: 2000,
      uploaded: "300GB",
      ratio: 0,
      privilege: "Create polls; Delete tags",
    },
    {
      id: 10,
      name: "Patriarch / Matriarch",
      bonus: 1500000,
      uploads: 3000,
      uploaded: "500GB",
      ratio: 0,
      privilege: "6 Personal collages; Create a forum (with staff approval of topic)",
    },
    {
      id: 11,
      name: "Torrent Master",
      bonus: 3000000,
      uploads: 5000,
      uploaded: "2TB",
      ratio: 0,
      privilege: "Torrent Master forum; 7 Personal collages; Project Team invite; Forum double post",
    },
    {
      id: 12,
      name: "Senior Torrent Master",
      bonus: 5000000,
      uploads: 7500,
      uploaded: "3TB",
      ratio: 0,
      privilege: "8 Personal collages; Submit a contest",
    },
    {
      id: 13,
      name: "Elite Torrent Master",
      bonus: 10000000,
      uploads: 10000,
      uploaded: "5TB",
      ratio: 0,
      privilege: "9 Personal collages; Request debug info; JPS Blue horse badge",
    },
    {
      id: 14,
      name: "Overlord / Dame",
      bonus: 15000000,
      uploads: 15000,
      uploaded: "10TB",
      ratio: 0,
      privilege: "Unlimited collages & invites; Custom badge; Create multiple forums",
    },
    {
      id: 15,
      name: "Torrent God / Goddess",
      bonus: 50000000,
      uploads: 20000,
      uploaded: "50TB",
      ratio: 0,
      privilege: "Custom forum header colour; Personal class name; Secret perks",
    },
  ],
};
