import { type ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "tey",
  name: "tey",
  aka: ["太乙"],
  description: "心不空则丹不结",
  tags: ["电视剧", "韩剧"],
  timezoneOffset: "+0800",

  collaborator: ["doubly-yi"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://cg.grl.pp/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { value: "401", name: "Movies" },
        { value: "402", name: "TV Series" },
        { value: "404", name: "Documentaries" },
        { value: "403", name: "TV Shows" },
        { value: "405", name: "Animations" },
        { value: "407", name: "Sports" },
        { value: "406", name: "Music Videos" },
        { value: "408", name: "HQ Audio" },
        { value: "409", name: "other" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { value: "1", name: "8K" },
        { value: "2", name: "4K" },
        { value: "3", name: "1080p" },
        { value: "4", name: "1080i" },
        { value: "5", name: "720p" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { value: "1", name: "WEB-DL" },
        { value: "2", name: "HDTV" },
        { value: "3", name: "Remux" },
        { value: "4", name: "MiniBD" },
        { value: "5", name: "HDTV" },
        { value: "6", name: "DVDR" },
        { value: "7", name: "Encode" },
        { value: "8", name: "CD" },
        { value: "9", name: "Track" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { value: "2", name: "H.264(x264/AVC)" },
        { value: "3", name: "H.265(x265/HEVC)" },
        { value: "4", name: "MPEG-2" },
        { value: "5", name: "VP8/9" },
        { value: "1", name: "Other" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { value: "2", name: "DTS-HDMA:X 7.1" },
        { value: "3", name: "DTS-HDMA" },
        { value: "4", name: "DTS" },
        { value: "5", name: "TrueHD Atmos" },
        { value: "6", name: "TrueHD" },
        { value: "7", name: "E-AC3 Atmos(DDP Atmos)" },
        { value: "8", name: "E-AC3(DDP)" },
        { value: "9", name: "AC3(DD)" },
        { value: "10", name: "AAC" },
        { value: "1", name: "Other" },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { value: "1", name: "Tey" },
        { value: "2", name: "CHD" },
        { value: "3", name: "MySiLU" },
        { value: "4", name: "WiKi" },
        { value: "5", name: "Other" },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别；只能在每周六中午12点至每周日晚上11点59分发布种子",
    },
    {
      id: 1,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 600000,
      privilege:
        '可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 2,
      name: "Elite User",
      interval: "P8W",
      downloaded: "500GB",
      ratio: 1.55,
      seedingBonus: 700000,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "1000GB",
      ratio: 4.05,
      seedingBonus: 800000,
      privilege: "可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      interval: "P25W",
      seedingBonus: 900000,
      downloaded: "2000GB",
      ratio: 4.55,
      privilege: "可以查看普通日志。",
    },
    {
      id: 5,
      name: "Veteran User",
      interval: "P40W",
      seedingBonus: 1000000,
      downloaded: "3000GB",
      ratio: 5.05,
      privilege: "可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "Extreme User",
      interval: "P60W",
      seedingBonus: 2000000,
      downloaded: "4TB",
      ratio: 5.55,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 7,
      name: "Ultimate User",
      interval: "P80W",
      seedingBonus: 3000000,
      downloaded: "5TB",
      ratio: 6.05,
      privilege: "无",
    },
    {
      id: 8,
      name: "Nexus Master",
      interval: "P100W",
      seedingBonus: 4000000,
      downloaded: "6TB",
      ratio: 6.55,
      privilege: "得到十个邀请名额。",
    },
  ],
};
