import type { ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "tokyopt",
  name: "Tokyo",
  tags: ["综合", "影视"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://jjj.gbxlbcg.klm/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "音乐", value: 408 },
        { name: "其他", value: 409 },
        { name: "MV", value: 406 },
        { name: "电视剧", value: 402 },
        { name: "动漫", value: 405 },
        { name: "电影", value: 401 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "WEB-DL", value: 10 },
        { name: "Track", value: 9 },
        { name: "CD", value: 8 },
        { name: "DVD", value: 6 },
        { name: "HDTV", value: 5 },
        { name: "Blu-ray", value: 1 },
        { name: "Encode", value: 7 },
        { name: "Remux", value: 3 },
        { name: "UHD Blu-ray", value: 2 },
        { name: "Other", value: 11 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "H.264/AVC", value: 1 },
        { name: "H.265/HEVC", value: 2 },
        { name: "VC-1", value: 3 },
        { name: "MPEG-2", value: 4 },
        { name: "AV1", value: 6 },
        { name: "Other", value: 5 },
        { name: "x265", value: 7 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "AV3V", value: 19 },
        { name: "OPUS", value: 18 },
        { name: "ALAC", value: 5 },
        { name: "AAC", value: 6 },
        { name: "APE", value: 17 },
        { name: "TrueHD Atmos", value: 16 },
        { name: "DDP/E-AC3", value: 15 },
        { name: "DD/AC3", value: 14 },
        { name: "LPCM", value: 13 },
        { name: "TrueHD", value: 12 },
        { name: "DTS:X", value: 11 },
        { name: "DTS-HD MA", value: 10 },
        { name: "DTS", value: 3 },
        { name: "M4A", value: 9 },
        { name: "WAV", value: 8 },
        { name: "MP3", value: 4 },
        { name: "FLAC", value: 1 },
        { name: "Other", value: 7 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "480p/480i", value: 7 },
        { name: "720p/720i", value: 3 },
        { name: "1080p/1080i", value: 1 },
        { name: "4K/2160p/2160i", value: 6 },
        { name: "8K/4320p/4320i", value: 5 },
        { name: "Other", value: 4 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "桜都字幕组", value: 8 },
        { name: "KitaujiSub", value: 7 },
        { name: "WiKi", value: 4 },
        { name: "MySiLU", value: 3 },
        { name: "HDS", value: 1 },
        { name: "CHD", value: 2 },
        { name: "Other", value: 5 },
        { name: "EastWeb", value: 6 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  levelRequirements: [
    {
      id: 1,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      privilege:
        '得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以发送邀请； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 2,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      privilege: "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      privilege: "可以查看普通日志。",
    },
    {
      id: 5,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 3.55,
      privilege: "可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 7,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 4.05,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 8,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 4.55,
      privilege: "得到十个邀请名额。",
    },
  ],
};
