import { type ISiteMetadata } from "../types";
import { SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "vclib",
  name: "VC-Lib",
  description: "专注于虚拟歌姬 （非虚拟偶像）相关内容的站点，禁R18",
  tags: ["虚拟歌姬", "音乐", "影视"],

  type: "private",
  schema: "NexusPHP",

  urls: ["https://pt.vclib.online/"],

  levelRequirements: [
    {
      id: 0,
      name: "一重加害",
      nameAka: ["User"],
      privilege: "新用户的默认级别",
    },
    {
      id: 1,
      name: "二重变革",
      nameAka: ["Power User"],
      interval: "P4W",
      seedingBonus: 40000,
      downloaded: "50GB",
      ratio: 1,
      privilege: "可以开始邀请新用户",
    },
    {
      id: 2,
      name: "三重爱恋",
      nameAka: ["Elite User"],
      interval: "P8W",
      seedingBonus: 100000,
      downloaded: "100GB",
      ratio: 2,
      privilege: "Elite User及以上用户封存账号后不会被删除。",
    },
    {
      id: 3,
      name: "四重罪孽",
      nameAka: ["Crazy User"],
      interval: "P15W",
      seedingBonus: 300000,
      downloaded: "150GB",
      ratio: 3,
    },
    {
      id: 4,
      name: "五重空洞",
      nameAka: ["Insane User"],
      interval: "P25W",
      seedingBonus: 500000,
      downloaded: "200GB",
      ratio: 4,
    },
    {
      id: 5,
      name: "六重不忠",
      nameAka: ["Veteran User"],
      interval: "P40W",
      seedingBonus: 1000000,
      downloaded: "250GB",
      ratio: 5,
      isKept: true,
      privilege: "Veteran User及以上用户会永远保留账号。",
    },
    {
      id: 6,
      name: "七重痼病",
      nameAka: ["Extreme User"],
      interval: "P60W",
      seedingBonus: 1500000,
      downloaded: "300GB",
      ratio: 6,
      isKept: true,
    },
    {
      id: 7,
      name: "八重回归",
      nameAka: ["Ultimate User"],
      interval: "P80W",
      seedingBonus: 2000000,
      downloaded: "350GB",
      ratio: 6,
      isKept: true,
    },
    {
      id: 8,
      name: "九重现实",
      nameAka: ["Nexus Master"],
      interval: "P100W",
      seedingBonus: 5000000,
      downloaded: "400GB",
      ratio: 8,
      isKept: true,
    },
  ],
};
