import { type ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP.ts";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,

  version: 1,
  id: "wintersakura",
  name: "WinterSakura",
  aka: ["冬樱"],
  tags: ["电影", "电视剧"],
  timezoneOffset: "+0800",

  collaborator: ["zhuweitung"],

  type: "private",
  schema: "NexusPHP",

  urls: ["uggcf://jvagrefnxhen.arg/"],

  category: [
    {
      name: "分类",
      key: "cat",
      options: [
        { name: "Misc/其他", value: 409 },
        { name: "Sports/体育", value: 407 },
        { name: "Music Videos/音乐MV", value: 406 },
        { name: "HQ Audio/无损音乐", value: 408 },
        { name: "TV Shows/综艺(分集）", value: 418 },
        { name: "TV Shows/综艺(合集)", value: 403 },
        { name: "TV Series/剧集(分集）", value: 402 },
        { name: "TV Series/剧集(合集）", value: 414 },
        { name: "Animation series/动漫剧集(分集)", value: 413 },
        { name: "Animation series/动漫剧集(合集)\t", value: 423 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "媒介",
      key: "medium",
      options: [
        { name: "Webrip", value: 25 },
        { name: "3D Blu-ray", value: 24 },
        { name: "SACD", value: 22 },
        { name: "CD", value: 18 },
        { name: "DVDR", value: 17 },
        { name: "HDTV", value: 16 },
        { name: "HD DVD", value: 23 },
        { name: "WEB-DL", value: 21 },
        { name: "Encode", value: 15 },
        { name: "Remux", value: 14 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "编码",
      key: "codec",
      options: [
        { name: "Other", value: 13 },
        { name: "ProRes", value: 15 },
        { name: "AV1", value: 16 },
        { name: "MPEG-2", value: 11 },
        { name: "VC-1", value: 10 },
        { name: "x264", value: 8 },
        { name: "x265", value: 7 },
        { name: "H264/AVC", value: 6 },
        { name: "H265/HEVC", value: 9 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "音频编码",
      key: "audiocodec",
      options: [
        { name: "Other", value: 21 },
        { name: "Opus", value: 27 },
        { name: "Dolby Digital Plus Dolby Atmos", value: 26 },
        { name: "Dolby Digital Plus", value: 25 },
        { name: "DSD", value: 24 },
        { name: "WAV", value: 23 },
        { name: "DTS-HD HR", value: 22 },
        { name: "AC3/DD", value: 20 },
        { name: "AAC", value: 19 },
        { name: "OGG", value: 18 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "分辨率",
      key: "standard",
      options: [
        { name: "SD", value: 4 },
        { name: "720p", value: 3 },
        { name: "1080i", value: 2 },
        { name: "2K/1080p", value: 1 },
        { name: "4K/2160p", value: 5 },
        { name: "8K/4320p", value: 6 },
      ],
      cross: { mode: "append" },
    },
    {
      name: "制作组",
      key: "team",
      options: [
        { name: "Other/其他制作组或转发资源", value: 5 },
        { name: "tjupt", value: 17 },
        { name: "PTer", value: 8 },
        { name: "FRDS", value: 7 },
        { name: "CMCT", value: 6 },
        { name: "ttg", value: 15 },
        { name: "Mteam", value: 13 },
        { name: "HDC", value: 14 },
        { name: "HDS", value: 1 },
        { name: "CHD", value: 2 },
      ],
      cross: { mode: "append" },
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  officialGroupPattern: ["SakuraWEB", "SakuraSUB", "WScode"],

  levelRequirements: [
    {
      id: 0,
      name: "User",
      privilege: "新用户的默认级别；可以上传的字幕",
    },
    {
      id: 1,
      name: "Power User",
      downloaded: "50GB",
      ratio: 1.0,
      seedingBonus: 50000,
      privilege:
        "可以查看NFO文档；可以请求续种； 可以购买/发送邀请；可以删除自己上传的字幕。可以申请友情链接；可以使用个性条。",
    },
    {
      id: 2,
      name: "Elite User",
      downloaded: "400GB",
      ratio: 1.5,
      seedingBonus: 120000,
      privilege: "可以查看种子结构；可以更新外部信息",
    },
    {
      id: 3,
      name: "Crazy User",
      downloaded: "800GB",
      ratio: 2.0,
      seedingBonus: 200000,
      privilege: "可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 4,
      name: "Insane User",
      downloaded: "1.5TB",
      ratio: 3.0,
      seedingBonus: 500000,
      privilege: "可以查看排行榜。",
    },
    {
      id: 5,
      name: "Veteran User",
      downloaded: "3TB",
      ratio: 4.0,
      seedingBonus: 800000,
      privilege: "可以查看其它用户种子历史。（只有用户的隐私等级没有设为’强‘时才生效）",
    },
    {
      id: 6,
      name: "Extreme User",
      downloaded: "5TB",
      ratio: 6.0,
      seedingBonus: 1400000,
      privilege: "可以更新过期的外部信息。Extreme User 及以上用户封存账号后不会被删除",
    },
    {
      id: 7,
      name: "Ultimate User",
      downloaded: "6TB",
      ratio: 8.0,
      seedingBonus: 2000000,
      privilege: "首次到达此等级得到1个邀请名额。",
    },
    {
      id: 8,
      name: "Nexus Master",
      downloaded: "10TB",
      ratio: 9.5,
      seedingBonus: 2800000,
      privilege: "首次到达此等级得到1个邀请名额Nexus Master及以上用户会永远保留账号。",
    },
  ],
};
