import type { ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,

  id: "xingtan",
  name: "杏坛",
  aka: ["杏林", "XingTan"],
  description: "杏坛 - 积少成多，聚沙成塔。",
  tags: ["医学", "电子书", "学术"],
  timezoneOffset: "+0800",

  type: "private",
  schema: "NexusPHP",

  collaborator: ["koal", "yum", "hui-shao"],

  urls: ["uggcf://kvatgna.bar/"],
  legacyUrls: ["https://xinglin.one/"],

  category: [
    {
      name: "专业类",
      key: "boxId_a",
      options: [
        { value: 123, name: "全部" },
        { value: 7, name: "医学" },
        { value: 8, name: "工学" },
        { value: 9, name: "理学" },
        { value: 10, name: "农学" },
        { value: 11, name: "经济学" },
        { value: 12, name: "管理学" },
        { value: 13, name: "法学" },
        { value: 14, name: "教育学" },
        { value: 15, name: "文学" },
        { value: 16, name: "哲学" },
        { value: 31, name: "历史学" },
        { value: 32, name: "艺术学" },
        { value: 115, name: "军事学" },
        { value: 101, name: "专业其它" },
        { value: 102, name: "内科系统" },
        { value: 103, name: "外科系统" },
        { value: 104, name: "妇产儿科" },
        { value: 110, name: "基础科研" },
        { value: 106, name: "中医综合" },
        { value: 107, name: "医技学科" },
        { value: 105, name: "临床其它" },
        { value: 108, name: "药学考培" },
        { value: 109, name: "公卫保健" },
        { value: 111, name: "医学其他" },
        { value: 67, name: "核工兵器" },
        { value: 66, name: "水利测绘" },
        { value: 65, name: "力学土木" },
        { value: 64, name: "计算机" },
        { value: 99, name: "电脑技术" },
        { value: 98, name: "电脑科学" },
        { value: 63, name: "轻工自控" },
        { value: 62, name: "电信通讯" },
        { value: 61, name: "能源动力" },
        { value: 59, name: "电气仪器" },
        { value: 68, name: "化工制药" },
        { value: 69, name: "地质矿油" },
        { value: 70, name: "农业林业" },
        { value: 73, name: "环境交通" },
        { value: 71, name: "生物食品" },
        { value: 58, name: "机械光学" },
        { value: 72, name: "海洋航空" },
        { value: 100, name: "材料冶金" },
        { value: 97, name: "公安安全" },
        { value: 96, name: "纺织建筑" },
        { value: 56, name: "统计学" },
        { value: 45, name: "数学" },
        { value: 46, name: "物理学" },
        { value: 47, name: "化学" },
        { value: 55, name: "心理学" },
        { value: 54, name: "生物学" },
        { value: 53, name: "地质学" },
        { value: 52, name: "地球物理" },
        { value: 51, name: "海洋学" },
        { value: 50, name: "大气学" },
        { value: 49, name: "地理学" },
        { value: 48, name: "天文学" },
        { value: 116, name: "系统科学" },
        { value: 79, name: "水产学" },
        { value: 78, name: "林学" },
        { value: 77, name: "动物医学" },
        { value: 76, name: "动物生产" },
        { value: 75, name: "自然环境" },
        { value: 74, name: "植物生产" },
        { value: 80, name: "草学" },
        { value: 112, name: "理论经济" },
        { value: 113, name: "应用经济" },
        { value: 82, name: "工商管理" },
        { value: 83, name: "农业经管" },
        { value: 84, name: "公共管理" },
        { value: 85, name: "图书档案" },
        { value: 87, name: "物流电商" },
        { value: 88, name: "工业工程" },
        { value: 89, name: "旅游管理" },
        { value: 81, name: "管理工程" },
        { value: 35, name: "政治学" },
        { value: 39, name: "公安学" },
        { value: 38, name: "马哲理论" },
        { value: 37, name: "民族学" },
        { value: 36, name: "社会学" },
        { value: 34, name: "法学" },
        { value: 41, name: "体育学" },
        { value: 40, name: "教育学" },
        { value: 44, name: "新闻传播" },
        { value: 43, name: "外语文学" },
        { value: 42, name: "中语文学" },
        { value: 91, name: "艺术理论" },
        { value: 95, name: "美术设计" },
        { value: 94, name: "戏剧影视" },
        { value: 93, name: "音乐舞蹈" },
        { value: 122, name: "后勤装备" },
        { value: 121, name: "军制政治" },
        { value: 120, name: "战术指挥" },
        { value: 119, name: "战略战役" },
        { value: 118, name: "思想历史" },
      ],
      cross: { mode: "append", key: "boxId" },
    },
    {
      name: "学术类",
      key: "boxId_b",
      options: [
        { value: 124, name: "全部" },
        { value: 125, name: "医学" },
        { value: 126, name: "工学" },
        { value: 127, name: "理学" },
        { value: 128, name: "农学" },
        { value: 129, name: "经济学" },
        { value: 130, name: "管理学" },
        { value: 131, name: "法学" },
        { value: 132, name: "教育学" },
        { value: 133, name: "文学" },
        { value: 134, name: "哲学" },
        { value: 135, name: "历史学" },
        { value: 136, name: "艺术学" },
        { value: 212, name: "军事学" },
        { value: 220, name: "学术其它" },
        { value: 200, name: "内科系统" },
        { value: 201, name: "外科系统" },
        { value: 202, name: "妇产儿科" },
        { value: 203, name: "临床其它" },
        { value: 204, name: "中医综合" },
        { value: 205, name: "医技学科" },
        { value: 206, name: "药学考培" },
        { value: 207, name: "公卫保健" },
        { value: 209, name: "医学其他" },
        { value: 208, name: "基础科研" },
        { value: 161, name: "电气仪器" },
        { value: 160, name: "机械光学" },
        { value: 162, name: "能源动力" },
        { value: 163, name: "电信通讯" },
        { value: 172, name: "生物食品" },
        { value: 171, name: "农业林业" },
        { value: 170, name: "地质矿油" },
        { value: 169, name: "化工制药" },
        { value: 168, name: "核工兵器" },
        { value: 167, name: "水利测绘" },
        { value: 166, name: "力学土木" },
        { value: 165, name: "计算机" },
        { value: 197, name: "电脑技术" },
        { value: 196, name: "电脑科学" },
        { value: 164, name: "轻工自控" },
        { value: 198, name: "材料冶金" },
        { value: 195, name: "公安安全" },
        { value: 194, name: "纺织建筑" },
        { value: 174, name: "环境交通" },
        { value: 173, name: "海洋航空" },
        { value: 159, name: "统计学" },
        { value: 158, name: "心理学" },
        { value: 157, name: "生物学" },
        { value: 156, name: "地质学" },
        { value: 155, name: "地球物理" },
        { value: 154, name: "海洋学" },
        { value: 153, name: "大气学" },
        { value: 152, name: "地理学" },
        { value: 151, name: "天文学" },
        { value: 150, name: "化学" },
        { value: 149, name: "物理学" },
        { value: 148, name: "数学" },
        { value: 213, name: "系统科学" },
        { value: 181, name: "草学" },
        { value: 180, name: "水产学" },
        { value: 179, name: "林学" },
        { value: 178, name: "动物医学" },
        { value: 177, name: "动物生产" },
        { value: 176, name: "自然环境" },
        { value: 175, name: "植物生产" },
        { value: 211, name: "应用经济" },
        { value: 210, name: "理论经济" },
        { value: 182, name: "管理工程" },
        { value: 183, name: "工商管理" },
        { value: 184, name: "农业经管" },
        { value: 189, name: "旅游管理" },
        { value: 188, name: "工业工程" },
        { value: 187, name: "物流电商" },
        { value: 186, name: "图书档案" },
        { value: 185, name: "公共管理" },
        { value: 139, name: "社会学" },
        { value: 138, name: "政治学" },
        { value: 137, name: "法学" },
        { value: 140, name: "民族学" },
        { value: 141, name: "马哲理论" },
        { value: 142, name: "公安学" },
        { value: 144, name: "体育学" },
        { value: 143, name: "教育学" },
        { value: 147, name: "新闻传播" },
        { value: 146, name: "外语文学" },
        { value: 145, name: "中语文学" },
        { value: 193, name: "美术设计" },
        { value: 192, name: "戏剧影视" },
        { value: 191, name: "音乐舞蹈" },
        { value: 190, name: "艺术理论" },
        { value: 218, name: "后勤装备" },
        { value: 217, name: "军制政治" },
        { value: 216, name: "战术指挥" },
        { value: 215, name: "战略战役" },
        { value: 214, name: "思想历史" },
      ],
      cross: { mode: "append", key: "boxId" },
    },
    {
      name: "标签",
      key: "tag_id",
      options: [
        { value: 9, name: "确认" },
        { value: 12, name: "修正" },
        { value: 1, name: "付费" },
        { value: 3, name: "官方" },
        { value: 2, name: "首发" },
        { value: 13, name: "原创" },
        { value: 39, name: "繁体" },
        { value: 10, name: "英语" },
        { value: 6, name: "中字" },
        { value: 8, name: "英文" },
        { value: 19, name: "应求" },
      ],
      cross: false,
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      bonus: {
        selector: ["td.rowhead:contains('杏仁值') + td", "td.rowhead:contains('Karma'):contains('Points') + td"],
        filters: [{ name: "parseNumber" }],
      },
      bonusPerHour: {
        selector: [
          "div:contains('你当前每小时能获取'):last",
          "div:contains('You are currently getting'):last",
          "div:contains('你當前每小時能獲取'):last",
        ],
        filters: [{ name: "parseNumber" }],
      },
    },
  },

  levelRequirements: [
    {
      id: 1,
      name: "Peasant",
      privilege:
        "被降级的用户，他们有15天时间来提升分享率，否则他们会被踢。不能发表趣味盒内容；不能申请友情链接；不能上传字幕。",
    },
    {
      id: 2,
      name: "User",
      privilege: "新用户的默认级别。",
    },
    {
      id: 3,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 14888,
      privilege:
        '得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 4,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 29888,
      privilege: "",
    },
    {
      id: 5,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 59888,
      privilege: "CrazyUser及以上用户封存账号后不会被删除；得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 6,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 118888,
      privilege: "可以查看普通日志。",
    },
    {
      id: 7,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 236888,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。",
    },
    {
      id: 8,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 3.55,
      seedingBonus: 468888,
      isKept: true,
      privilege: "Extreme User及以上等级用户会永远保留；可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 9,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 4.05,
      seedingBonus: 988888,
      isKept: true,
      privilege: "得到四个邀请名额。",
    },
    {
      id: 10,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 4.55,
      seedingBonus: 1888888,
      isKept: true,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 100,
      groupType: "vip",
      name: "贵宾(VIP)",
      privilege: "和Nexus Master拥有相同权限并被认为是精英成员。免除自动降级。",
    },
    {
      id: 200,
      groupType: "manager",
      name: "养老族(Retiree)",
      privilege: "退休后的管理组成员。",
    },
    {
      id: 201,
      groupType: "manager",
      name: "发布员(Uploader)",
      privilege: "专注的发布者。免除自动降级；可以查看匿名用户的真实身份。",
    },
    {
      id: 202,
      groupType: "manager",
      name: "总版主(Moderator)",
      privilege:
        "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。不能管理友情链接、最近消息、论坛版块；不能将种子设为置顶或促销；不能查看用户IP或Email等机密信息；不能删除账号。",
    },
    {
      id: 203,
      groupType: "manager",
      name: "管理员(Administrator)",
      privilege: "除了不能改变站点设定、管理捐赠外，可以做任何事。",
    },
    {
      id: 204,
      groupType: "manager",
      name: "维护开发员(Sysop)",
      privilege: "网站开发/维护人员，可以改变站点设定，不能管理捐赠。",
    },
    {
      id: 205,
      groupType: "manager",
      name: "主管(Staff Leader)",
      privilege: "网站主管，可以做任何事。",
    },
  ],
};
