import type { ISiteMetadata } from "../types";
import { CategoryInclbookmarked, CategoryIncldead, CategorySpstate, SchemaMetadata } from "../schemas/NexusPHP";

export const siteMetadata: ISiteMetadata = {
  ...SchemaMetadata,
  version: 1,

  id: "xingtan",
  name: "杏坛",
  aka: ["杏林"],
  description: "杏坛 - 积少成多，聚沙成塔。",
  tags: ["医学", "电子书", "学术"],
  timezoneOffset: "+0800",

  type: "private",
  schema: "NexusPHP",

  collaborator: ["koal", "yum", "hui-shao"],

  urls: ["uggcf://kvatgna.bar/"],
  formerHosts: ["xinglin.one"],

  category: [
    {
      name: "专业类",
      key: "boxId_a",
      options: [
        { value: 123, name: "全部" },
        { value: 7, name: "医学" },
        { value: 8, name: "工学" },
        { value: 9, name: "理学" },
        { value: 10, name: "农学" },
        { value: 11, name: "经济学" },
        { value: 12, name: "管理学" },
        { value: 13, name: "法学" },
        { value: 14, name: "教育学" },
        { value: 15, name: "文学" },
        { value: 16, name: "哲学" },
        { value: 31, name: "历史学" },
        { value: 32, name: "艺术学" },
        { value: 115, name: "军事学" },
        { value: 101, name: "专业其它" },
      ],
      cross: { mode: "append", key: "boxId" },
    },
    {
      name: "学术类",
      key: "boxId_b",
      options: [
        { value: 124, name: "全部" },
        { value: 125, name: "医学" },
        { value: 126, name: "工学" },
        { value: 127, name: "理学" },
        { value: 128, name: "农学" },
        { value: 129, name: "经济学" },
        { value: 130, name: "管理学" },
        { value: 131, name: "法学" },
        { value: 132, name: "教育学" },
        { value: 133, name: "文学" },
        { value: 134, name: "哲学" },
        { value: 135, name: "历史学" },
        { value: 136, name: "艺术学" },
        { value: 212, name: "军事学" },
        { value: 220, name: "学术其它" },
      ],
      cross: { mode: "append", key: "boxId" },
    },
    {
      name: "标签",
      key: "tag_id",
      options: [
        { value: 9, name: "确认" },
        { value: 12, name: "修正" },
        { value: 1, name: "付费" },
        { value: 3, name: "官方" },
        { value: 2, name: "首发" },
        { value: 13, name: "原创" },
        { value: 39, name: "繁体" },
        { value: 10, name: "英语" },
        { value: 6, name: "中字" },
        { value: 8, name: "英文" },
        { value: 19, name: "应求" },
      ],
      cross: false,
    },
    CategoryIncldead,
    CategorySpstate,
    CategoryInclbookmarked,
  ],

  userInfo: {
    ...SchemaMetadata.userInfo!,
    selectors: {
      ...SchemaMetadata.userInfo!.selectors!,
      bonus: {
        selector: ["td.rowhead:contains('杏仁值') + td", "td.rowhead:contains('Karma'):contains('Points') + td"],
        filters: [{ name: "parseNumber" }],
      },
      bonusPerHour: {
        selector: [
          "div:contains('你当前每小时能获取'):last",
          "div:contains('You are currently getting'):last",
          "div:contains('你當前每小時能獲取'):last",
        ],
        filters: [{ name: "parseNumber" }],
      },
    },
  },

  levelRequirements: [
    {
      id: 1,
      name: "Peasant",
      privilege:
        "被降级的用户，他们有15天时间来提升分享率，否则他们会被踢。不能发表趣味盒内容；不能申请友情链接；不能上传字幕。",
    },
    {
      id: 2,
      name: "User",
      privilege: "新用户的默认级别。",
    },
    {
      id: 3,
      name: "Power User",
      interval: "P4W",
      downloaded: "50GB",
      ratio: 1.05,
      seedingBonus: 14888,
      privilege:
        '得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种； 可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为"强")； 可以删除自己上传的字幕。',
    },
    {
      id: 4,
      name: "Elite User",
      interval: "P8W",
      downloaded: "120GB",
      ratio: 1.55,
      seedingBonus: 29888,
      privilege: "",
    },
    {
      id: 5,
      name: "Crazy User",
      interval: "P15W",
      downloaded: "300GB",
      ratio: 2.05,
      seedingBonus: 59888,
      privilege: "CrazyUser及以上用户封存账号后不会被删除；得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。",
    },
    {
      id: 6,
      name: "Insane User",
      interval: "P25W",
      downloaded: "500GB",
      ratio: 2.55,
      seedingBonus: 118888,
      privilege: "可以查看普通日志。",
    },
    {
      id: 7,
      name: "Veteran User",
      interval: "P40W",
      downloaded: "750GB",
      ratio: 3.05,
      seedingBonus: 236888,
      privilege: "得到三个邀请名额；可以查看其它用户的评论、帖子历史。",
    },
    {
      id: 8,
      name: "Extreme User",
      interval: "P60W",
      downloaded: "1TB",
      ratio: 3.55,
      seedingBonus: 468888,
      privilege: "Extreme User及以上等级用户会永远保留；可以更新过期的外部信息；可以查看Extreme User论坛。",
    },
    {
      id: 9,
      name: "Ultimate User",
      interval: "P80W",
      downloaded: "1.5TB",
      ratio: 4.05,
      seedingBonus: 988888,
      privilege: "得到四个邀请名额。",
    },
    {
      id: 10,
      name: "Nexus Master",
      interval: "P100W",
      downloaded: "3TB",
      ratio: 4.55,
      seedingBonus: 1888888,
      privilege: "得到五个邀请名额。",
    },
    {
      id: 100,
      groupType: "vip",
      name: "贵宾(VIP)",
      privilege: "和Nexus Master拥有相同权限并被认为是精英成员。免除自动降级。",
    },
    {
      id: 200,
      groupType: "manager",
      name: "养老族(Retiree)",
      privilege: "退休后的管理组成员。",
    },
    {
      id: 201,
      groupType: "manager",
      name: "发布员(Uploader)",
      privilege: "专注的发布者。免除自动降级；可以查看匿名用户的真实身份。",
    },
    {
      id: 202,
      groupType: "manager",
      name: "总版主(Moderator)",
      privilege:
        "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。不能管理友情链接、最近消息、论坛版块；不能将种子设为置顶或促销；不能查看用户IP或Email等机密信息；不能删除账号。",
    },
    {
      id: 203,
      groupType: "manager",
      name: "管理员(Administrator)",
      privilege: "除了不能改变站点设定、管理捐赠外，可以做任何事。",
    },
    {
      id: 204,
      groupType: "manager",
      name: "维护开发员(Sysop)",
      privilege: "网站开发/维护人员，可以改变站点设定，不能管理捐赠。",
    },
    {
      id: 205,
      groupType: "manager",
      name: "主管(Staff Leader)",
      privilege: "网站主管，可以做任何事。",
    },
  ],
};
